### ISSUE TITLE
Mks sbase.

### ISSUE THREAD

**Issue by mrjoe909** [makerbase-mks/MKS-SBASE#10]
My board has will not respond. All the lights turn on with or without an sd card. The sd card is formated to fat32. Everything was working great, them it stopped working. Any information would be greatly appreciated

**Comment by mrjoe909** [comment]
Board was purchased 2016 03 30

**Comment by pixel3design-hub** [comment]
Contact the seller. This is not for warranty purpose.

**Comment by makerbase-mks** [comment]
please contact :  shelly@makerbase.com.cn   thanks.
