### ISSUE TITLE
MKS sbase with MKS mini 12864 LCD

### ISSUE THREAD

**Issue by hussainsail2002** [makerbase-mks/MKS-SBASE#101]
I am unable to get the MKS sbase working with MKS mini 12864 LCD.

I assumed that since both were MKS make it would be compatible. I realized now that the pins are not defined for this LCD.

Could some one help me out with this.

Regards,
Hussain

**Comment by makerbase-mks** [comment]
Hi, this you need change it of MKS SBASE（or MKS SGEN） board's EXP1 interface
1. Connect EXP1's pin5 and pin7、pin4 and pin6，As shown below
MKS SBASE(or MKS SGEN) pin map:
![image](https://user-images.githubusercontent.com/12979070/68524259-9e103600-02ff-11ea-8348-4f895cb3e100.png)
MKS MINI12864 pin map:
![image](https://user-images.githubusercontent.com/12979070/68524303-08c17180-0300-11ea-9980-2dd4a31158f9.png)
Welding effect picture:
![image](https://user-images.githubusercontent.com/12979070/68524395-64d8c580-0301-11ea-96df-cc1f1a718be5.png)
2. Pin define
Use Marlin fireware
Marlin -> src-> pins -> lpc1768 -> pins_MKS_SBASE.h add pin define
#define DOGLCD_CS      P0_16
#define DOGLCD_A0      P0_15
#define DOGLCD_SCK     P0_07
#define DOGLCD_MOSI    P0_09
![image](https://user-images.githubusercontent.com/12979070/68524461-25f73f80-0302-11ea-9d31-cd8e4324d5c3.png)
Use smoothieware
![image](https://user-images.githubusercontent.com/12979070/68524676-9acb7900-0304-11ea-9ab9-2ae6d6f96950.png)
3.Test effect chart
Marlin:
![image](https://user-images.githubusercontent.com/12979070/68524612-f0ebec80-0303-11ea-9d8b-755ad31af656.png)
![image](https://user-images.githubusercontent.com/12979070/68524615-fc3f1800-0303-11ea-9633-e5a4a0821a22.png)
Smoothieware:
![image](https://user-images.githubusercontent.com/12979070/68524631-0f51e800-0304-11ea-9cc8-fee490ef4e6b.png)
![image](https://user-images.githubusercontent.com/12979070/68524635-1d076d80-0304-11ea-8b1e-4b308da595b7.png)

**Comment by hussainsail2002** [comment]
@makerbase-mks 

Thanks for the reply,

I have another question. 
In the configuration file I need to activate minipanel right and not mks_mini_12864 ?

**Comment by hussainsail2002** [comment]
@makerbase-mks 

My LCD stays on only for few seconds and then shuts off

Any reason for this ?

Hussain

**Comment by makerbase-mks** [comment]
No, you only need enable MKS_MINI12864 .
Can you give me your email address? I will send you my Marlin firmware to you.

**Comment by hussainsail2002** [comment]
my email id is hussain@3ding.in

**Comment by hussainsail2002** [comment]
I got it working now thanks ! 

I activated mks_mini_12864 instead of minipanel

Edit:

I am closing the issue now.

**Comment by makerbase-mks** [comment]
OK

**Comment by davigre** [comment]
Trying to make it work on Smothieware...

I have MKS SBASE L v1 with original MKS Smothieware version: [https://github.com/makerbase-mks/MKS-SBASE/blob/master/English/firmware/firmware.bin](https://github.com/makerbase-mks/MKS-SBASE/blob/master/English/firmware/firmware.bin) (is the only one that has worked for me and the one that @makerbase-mks  are showing in the photo)

I have MKS MINI12684 v1.

I do not solder pin5 and pin7 and pin4 and pin6, instead I bridge with cable connectors:

**MINI12864      <->       SBASE**
(DOGLCD_AO) <-> (P0.15)
(DOGLCD_CS) <-> (P0.16)
(BTN_NC) <-> (P1.30)
(BEEPER) <-> (P1.31)
(GND) <-> (GND)
(VCC) <-> (VCC)

EXT2 without modifications.

And with the following `config.txt`parameters:
```
panel.enable                                 true            # Set to true to enable the panel code
panel.lcd                                   st7565_glcd     #
panel.spi_channel                           1               # SPI channel to use  ; GLCD EXP1 Pins 3,5 (MOSI, SCLK)
panel.spi_cs_pin                            0.16            # SPI chip select     ; GLCD EXP1 Pin 4
panel.spi_frequency                         500000          # SPI port frequency - some panel need it explicitly set
panel.contrast                              0               # Contrast value for panels that support it ( viki2, mini_viki2 and st7565_glcd )
panel.encoder_resolution                    4               # the number of pulses the encoder emits per detent/click
panel.reverse                               true            # If set to true, reverse the screen.
panel.busy_pin                              nc              # If using the universal_adapter, this pin can be connected to the adapter to ask it if it is busy or not.
panel.a0_pin                                0.15            # (spi A0) If using a viki or SSD1306 this is needed to drive the C/D pin on the display
panel.rst_pin                               nc              # If using an SSD1306 this pin is sometimes required and connects to the reset pin on the display
panel.menu_offset		                    0               #

panel.encoder_a_pin                         3.25!^          # Encoder pin         ; GLCD EXP2 Pin 3
panel.encoder_b_pin                         3.26!^          # Encoder pin         ; GLCD EXP2 Pin 5
panel.click_button_pin                      1.30!^          # Click button        ; GLCD EXP1 Pin 2
panel.buzz_pin                              1.31            # Pin for buzzer      ; GLCD EXP1 Pin 1
#panel.back_button_pin                      2.11!^          # Back button         ; GLCD EXP2 Pin 8

panel.external_sd                           false           # set to true if there is an extrernal sdcard on the panel
panel.external_sd.spi_channel               1               # set spi channel the sdcard is on
panel.external_sd.spi_cs_pin                0.28            # set spi chip select for the sdcard (or any spare pin)
panel.external_sd.sdcd_pin                  0.27!^          # sd detect signal (set to nc if no sdcard detect) (or any spare pin)

panel.menu_offset                            1              # Some panels will need 1 here

panel.alpha_jog_feedrate                     6000           # X jogging feedrate in mm/min
panel.beta_jog_feedrate                      6000           # Y jogging feedrate in mm/min
panel.gamma_jog_feedrate                     200            # Z jogging feedrate in mm/min

panel.hotend_temperature                     200            # Temp to set hotend when preheat is selected
panel.bed_temperature                        70             # Temp to set bed when preheat is selected
```
I notice 'panel.menu_offset' is repeated. Which is the correct value?

I also notice that this parameters are different from here: [https://github.com/makerbase-mks/SGEN_L/blob/master/Firmware/Smoothieware/MKS%20MINI12864%20and%20MKS%20LCD12864A/config.txt](https://github.com/makerbase-mks/SGEN_L/blob/master/Firmware/Smoothieware/MKS%20MINI12864%20and%20MKS%20LCD12864A/config.txt)

The Display turns On but nothing appears. Beeper sounds as soon as I turn on the board or when I push the encoder button.

What more do I need to do?

**Comment by thiagoedson** [comment]
MKS_ROBIN_E3D_V1_1  ?
