### ISSUE TITLE
Mks Robin V2.1 TFT 1.0 Marlin bugfix 2.0 no screen

### ISSUE THREAD

**Issue by 3Dangel** [makerbase-mks/MKS-SBASE#102]
Would it be possible to get some help with the old Robin’s with TFT 1.0?
Your repository with the working TFT codes is good. But the rest of features are missing. 
Trying to use for Mixing features and the codes in your GitHub are way too old and not have the more complete features to and for mixing extruder with one nozzle. 

Would you be able to help?

Thank you in advance.

**Comment by makerbase-mks** [comment]
At present, Marlin does not have a good way to solve the TFT UI display image... full function, if you want to have UI function, you can only use the firmware that comes with Robin. This we will continue to pay attention.

**Comment by 3Dangel** [comment]
Thank you for your reply. 
Then would it be possible to have the pin out for the board?
At your GitHub repository, I can only find schematic first V2.3 & V2.4 board. 

Thanks you.

**Comment by makerbase-mks** [comment]
I will sort out the V2.2 or earlier version and post it to Github.

**Comment by 3Dangel** [comment]
closing the case.
Main Marlin branch has updated the codes for the ILI 9238 initialization of the TFT screen.
SO, now it is working
