### ISSUE TITLE
Issues on X surface

### ISSUE THREAD

**Issue by aceranic** [makerbase-mks/MKS-SBASE#103]
Hi,

I have issues on x surface. Both sides.
Till now checked mechanics, replaced all bearings, swapped motor, changed current, changed acceleration. Nothing helps.
Z axis is on 12mm rods and separated from screws so no way it is causing wobbling

Any ideas?

Thanks,

**Comment by aceranic** [comment]
![20191121_194659](https://user-images.githubusercontent.com/16923045/69367121-f0eed380-0c97-11ea-811a-a8cf7f86a154.jpg)

**Comment by 3Dangel** [comment]
May be speed to high.
And it might be your Y axis is you are certain that it is not the Z

**Comment by aceranic** [comment]
I reduced speed to 15mm/s and still same. On Y changed bearings and motor. Still same.
Z is separated from screws and is on 12mm linear rails.
I even swapped extruder with different one. Still same.
Driver issue? 

It is cartesian printer. 


To change Y axis to E1 I just need to change pin number from Beta to E1?
