### ISSUE TITLE
LPC1768 replace 

### ISSUE THREAD

**Issue by badyl00** [makerbase-mks/MKS-SBASE#104]
Hello. I have problem with MKS BASE v1.3 board. After print I saw temperatures from TH1 and TH2 giving strange values  (385 deg and 187 deg). I remove the board and saw a smal hole in LPC IC. I ordered new ic for change. If chip is replaced I need to program it or only insert SD card to slot ?

**Comment by makerbase-mks** [comment]
You need to flash BootLoader of LPC1768, Because Smoothie updating firmware by Bootloader.
You can refer to : https://tieba.baidu.com/p/4258590897
