### ISSUE TITLE
 firmware  Marlin-bugfix-2.0.x  błąd kompilacji 

### ISSUE THREAD

**Issue by qulet** [makerbase-mks/MKS-SBASE#108]
env_default = LPC1768
FIRMWARE NOT  compile!!!!!!!!!!!

compilation terminated due to -fmax-errors=5.
*** [.pioenvs\LPC1768\lib2d1\TMCStepper_ID5513\source\SW_SPI.cpp.o] Error 1

**Comment by makerbase-mks** [comment]
Use marlin 2.0 for MKS SBASE, you need set firmware like this:
1.  in configuration.h file   Set board is: #define MOTHERBOARD BOARD_MKS_SBASE
you try to build it
