### ISSUE TITLE
Mks Firmware.bin file

### ISSUE THREAD

**Issue by chris334** [makerbase-mks/MKS-SBASE#11]
The mks firmware.bin file doesn't fully work correctly, as my endstops was not being read so i went and got smoothie wares edge, im glad its not smoking or set on fire but come guys get these issues sorted as were are doing the hard work finding these problems and sorting them out

**Comment by taqisyed** [comment]
i had the same issue and updated firmware from smoothie website + started working with bCnc everything became normal. pronterface i didn't like.
