### ISSUE TITLE
Last Smothieware firmware doesn't work

### ISSUE THREAD

**Issue by davigre** [makerbase-mks/MKS-SBASE#110]
I'm using MKS-SBASE L v1 with Smothieware version: "Build version: edge-823faf1, Build date: Dec 27 2014 04:05:24, MCU: LPC1768, System Clock: 100MHz" and is working fine as a DELTA Printer driver.

I want to mount last Smothieware version so I mount this version: [https://github.com/Smoothieware/Smoothieware/blob/edge/FirmwareBin/firmware.bin](https://github.com/Smoothieware/Smoothieware/blob/edge/FirmwareBin/firmware.bin)

And I noticed blocking (freezing) problems when sending several GCODE's.

So then I return to the one in this repository: [https://github.com/makerbase-mks/MKS-SBASE/blob/master/English/firmware/firmware.bin](https://github.com/makerbase-mks/MKS-SBASE/blob/master/English/firmware/firmware.bin)

And started to work again.

Reading [issue 92](https://github.com/makerbase-mks/MKS-SBASE/issues/92) it says that I can use any Smothieware firmware, but I can't.

I also found the (MAKERBASE original) Smothieware source code here: [https://github.com/makerbase-mks/MKS-SBASE/blob/master/English/Source/Smoothieware-edge.rar](https://github.com/makerbase-mks/MKS-SBASE/blob/master/English/Source/Smoothieware-edge.rar), but too much work for me.

Please indicate me which is the last Smothieware firmware that I can use.

I don't want to use Marlin, I love 'config.txt' file configuration.

Thanks.

**Comment by 3Dangel** [comment]
Than purchase the original Smoothie board in order to be compatible.
MKS Sbase is NOT  supported by smoothie community.

**Comment by DivingDuck** [comment]
@davigre, had you use your old config file with the latest firmware?

**Comment by davigre** [comment]
@DivingDuck , Yes. I don't change it.

@3Dangel , I already start to learn Marlin. it looks too many configuration parameters. But I think is the way to go. Thanks.

**Comment by DivingDuck** [comment]
@davigre it's maybe worth to take over your values in a newly downloaded config.txt. I'm running the latest build on an core-xy both with SD card and USB via Pronterface (and Cura too) without any problem.

**Comment by davigre** [comment]
@DivingDuck ,

Thank's for encourage me. It finally works. 

The problem was not 'config.txt' file . I discovered that when I send M105 the following message was output:

```
MINTEMP or MAXTEMP triggered on B. Check your temperature sensors! HALT asserted - reset or M999 required
```
Searching, I found this: [http://smoothieware.org/temperaturecontrol#maximum-temperature-detection](http://smoothieware.org/temperaturecontrol#maximum-temperature-detection)

Found that my 'bed' thermistor was wrongly defined as 'Honeywell100K'.

I simple commented this line:

```
#temperature_control.bed.thermistor        Honeywell100K
```

Found also when executing 'version' command the following output:

```
Smoothie command shell
version
Build version: upstreamedge-c0d4117, Build date: Jul 31 2020 17:46:39, MCU: LPC1768, System Clock: 100MHz
5 axis
      NOTICE: This MCU is deprecated, and cannot guarantee proper function
```


Thanks.

**Comment by DivingDuck** [comment]
Thanks for your feedback. Happy printing.
