### ISSUE TITLE
LCD Compatability (2004 LCD with control board for ramps 1.4)

### ISSUE THREAD

**Issue by Fickert07** [makerbase-mks/MKS-SBASE#13]
Hi,

I have a Folger Tech FT-5 and upgraded to the sbase. I have installed a 2004 lcd with an sd card slot installed. I cannot for the life of me figure out how to correctly get this working. I have the lcd lit and all the character blocks lit as well, but not functionality comes of it. 

Is there a breakdown of the pinout of the sbase for the lcd pins? Also I am confused on how to interpret the panel settings in the config file. 

Thanks

**Comment by makerbase-mks** [comment]
sorry, 2004lcd can't be used on mks sbase.
you have to use 12864lcd or mks tft28/32
