### ISSUE TITLE
MKS SMINI VRef

### ISSUE THREAD

**Issue by mgozali** [makerbase-mks/MKS-SBASE#19]
I want to adjust stepper motor current.
What is vref to I formula for mks smini?

**Comment by ArchConMan** [comment]
MKS Smini v1.0
> 2.    12V input .
> 3.    Adjust drive current manually, it is not available to make it via program.
> 4.    4pcs HR4982 motor driver, default 1A.

such a mysterious board must have a secret formula. I want to believe.
