### ISSUE TITLE
Firmware. bin not updating

### ISSUE THREAD

**Issue by JimSVMI83** [makerbase-mks/MKS-SBASE#2]
copied config.txt and firmware.bin to SD- 64 gb inserted into board and powered on.  It has not changed the firmware.bin to firmware.cur.  Am I missing something?

**Comment by snowwolf725** [comment]
Please format your SD card to FAT32 (not NTFS )
https://www.youtube.com/watch?v=DuTlm17lvmw

**Comment by JimSVMI83** [comment]
Perfect fixed it

**Comment by makerbase-mks** [comment]
that's ok
