### ISSUE TITLE
SMINI doesnt flash

### ISSUE THREAD

**Issue by inzKrzys** [makerbase-mks/MKS-SBASE#21]
I try flashing firmware with 4 freshly formated to fat32 sd cards and its not working. File extension of firmware.bin stays the same.
(All of this cards works perfectly in other devices)
I try this on 3 win10 pc`s, with 32 and 64bit system and board doesnt show up in device menager.
I install windows drivers and nothing change.
I try entire procedure with and without external power source.

No matter what I do, led pattern stays the same:
- D5 and D6 (near mosfets) light up for 2 seconds and stays off for 2 seconds.
- D3 stays lit entire time
- D4 stays lit but barely visible

Is it possible that seller send board without bootloader?

Edit
I try entire procedure on win 8.1 and still no success.

**Comment by medicshort87** [comment]
Any resolution?

**Comment by inzKrzys** [comment]
Still no

**Comment by pixel3design-hub** [comment]
It could be...

**Comment by makerbase-mks** [comment]
@inzKrzys  Hvae you install the usb driver?

**Comment by pixel3design-hub** [comment]
post a photo pls.
There's no D5 D6 near mosfets. I suppose you got a different board.
MKS-SBASE LEDS:

        D7  D4  D3  D2  D1
        R7  R4   R3  R2  R1
uSD

ETHERNET
                                                  MCU

USB






                      D14                         D13                           D12                            D10

**Comment by inzKrzys** [comment]
@makerbase-mks 
Yes

@pixel3design-hub 
It is SMINI as it stands in title of thread. SMINI is the same as SBASE but without Ethernet and with less power outputs. Chinese manufacturer does'nt care to make separate chapter for this board and firmware is the same as in SBASE so I wrote here.
I have suspitions that board itself is broken but post cost to and from seller is worth same as board itself so meh ¯\\__(ツ)__/¯
![30180051_1205871886212189_511003990_n](https://user-images.githubusercontent.com/26596680/38368718-535a8db6-38e6-11e8-9b7b-dababcba17c3.png)

**Comment by pixel3design-hub** [comment]
Ok. On aux1 connector, TX and Rx to flash bootloader, close the boot jumper

**Comment by ArchConMan** [comment]
> Ok. On aux1 connector, TX and Rx to flash bootloader, close the boot jumper
![sminithis](https://user-images.githubusercontent.com/12946682/46003071-7f4fd100-c064-11e8-9371-4ca4f8a1fbfd.jpg)
boot jumper is what? that? I have the board, not much info, even less of a clue! Thanks.
