### ISSUE TITLE
Freeze without USB

### ISSUE THREAD

**Issue by ahmetipkin** [makerbase-mks/MKS-SBASE#22]
Hi. When I unplug the USB cable from the board, it runs for a few seconds, then stops and freezes (leds don't blink anymore) and then it triggers watchdog dead and turns off all the board and heaters - I cannot do anything unless I reset the board.

Is this normal? What can I do in order to make the board standalone as well (I don't want the pc to be turned on all the time when printing).

Thank you

**Comment by MD3DDelta** [comment]
Hello , do you print from the computer or from the sdcard in the panel /tft-screen?
when printing from computer , and you unplug the usb , then the printer handles correct .
the safty modus works .
when printing from sdcard , then your 5volt on board has an problem, i had in the past this problemm with rampsboards/mega , so i toke an usb-charger and putted the usbcable from the mega in and the problemm was gone. but when this not works the board is dammaged or an setting is wrong , the setting i don't know where it is , maybe you can find it in the orginal smoothie configfile and copy it to mks config.
hope you get it right.
greetz mike
