### ISSUE TITLE
Poor print quality, missing steps?

### ISSUE THREAD

**Issue by robustini** [makerbase-mks/MKS-SBASE#23]
Please read this post, need to know if it's a board (original MKS SBase V1.3) or firmware problem, thanks!

Marco

https://groups.google.com/forum/#!topic/smoothieware-support/jlJKE_zbgno

**Comment by MD3DDelta** [comment]
hi marco , if your printer is an delta then change this ;
delta_segments_per_second                    200              # for deltas only same as in Marlin/Delta, set to 0 to disable
                                                              # and use mm_per_line_segment

200 works very fine on mine delta selfbuild. same mks-sbase .
simply3d has some problems with smoothieware , but in the last update they had solved all problems?
maybe you find one again , ..
I have reduced current to 0.7 on all steppers , mine motors are nema 17 ,0.9degr 4,5kg.
they stay very cool ,about 30 degr celsius . and do not miss any steps any more . 

Hope it helpt you , gretings Mike.
