### ISSUE TITLE
PWN pin max current 

### ISSUE THREAD

**Issue by stanrob** [makerbase-mks/MKS-SBASE#24]
I everyone, 

I’m wondering what could be the max current that can deliver the PWM pin 1.23.
I want to add a controllable fan for my hotend heatsink and 2 to cool down my board. 
Those fans are 40mm 12V so not that big. Can those PWM pins handle it without adding a SSR or power extender?

**Comment by pixel3design-hub** [comment]
Nope.
Current is below 100mA @ 5V.
Easiest way is using a Mosfet or, much simpler, a BJT transistor. 
Indeed you can use one of the 12V PWM outputs for fans already present on the board (eg. E1 - FAN)

**Comment by stanrob** [comment]
Okay, thanks a lot. 
I already use every 12V pwm outpout (E1-E2-layer fan).
