### ISSUE TITLE
Set temperature changes when printing starts 

### ISSUE THREAD

**Issue by Press1now** [makerbase-mks/MKS-SBASE#28]
When I set the hot end temperature to 220 (C) and the hot bed to 100 (C) my display and program will show 220/220 and 100/100 respectively. But as soon as i start printing the set temperature from the MKS Sbase board changes it to  220/205 and 100/065 causing it to trigger a HALT message. What is causing this ?

**Comment by MD3DDelta** [comment]
You have to set the pid tuning , and check very carefull the connextion from the thermosthat ,( what gives the temp) , mine was just broken ,when got warm the error came like you ,
So i solderd all again and pidtunend , and the problem was gone .
pidtune look to smoothie page .
cheers mike

**Comment by Press1now** [comment]
Issue resolved, i was using Cura 2, and it was slicing the temperature of 100 and 65 respectively. Uninstalled it and went with another program.
