### ISSUE TITLE
sbase 1.3 extra steppers

### ISSUE THREAD

**Issue by Tertius91820** [makerbase-mks/MKS-SBASE#33]
Hi Guys

I'm currently running a core XY with dual extrusion.
Is there a way to implement 4 extruders?

Maybe external stepper expander boards via free pins?

And if free pins, which will be usable for 2 external stepper boards?

Thank you

**Comment by MD3DDelta** [comment]
Hello , i was looking for the same problem .
didn't find anything , when i find something i give you answer.
cheers mike

**Comment by Tertius91820** [comment]
Awesome thanks!

**Comment by Quas7** [comment]
http://smoothieware.org/multiple-extruders

looks like it should work with the sbase as well as gpio are available and firmware supports it very nicely

**Comment by pixel3design-hub** [comment]
I forked the SBASE repository.
Looking into, you'll find schematics, pinouts and something more.
Follow @Quas7 link and configure your extruders using free pins (normally you need 3 Px.x pins and one GND, so to use 4 extruders you need at least 9 data pins.
Some pins for LCD can be used too (if you own the MKSTFT) !!! WARNING !!! SOME OF THEM ARE NEEDED FOR MKSTFT TOO !!!
If you need more infos, post here and I'll be glad to help.

Cheers

**Comment by Tertius91820** [comment]
I'm using a driver for the x and a driver for y. Then I'm using one for two steppers on z. I've configured two extruders on the two other drivers e0 and e1. Where would I pin up for two more extruders?. I don't need thermal readings on separate extruders as I'm using one hotend like the Prusa...

**Comment by Tertius91820** [comment]
Thanks for the info the repository👍 

Also I'm using sbase 1.3 and a tft2.8.

**Comment by ovisopa** [comment]
I'm also interested if I can have 3 more extruders, if I will also purchase MKSTFT will the LCD1 and LCD2 headers be free ? 

If there is anyone that already tried, or knows for sure, please let us know what are the free pins we can use to drive at least 3 extruders

![image](https://user-images.githubusercontent.com/5344791/52569766-9c6e1c00-2e1a-11e9-8798-20ee6265ea7a.png)
