### ISSUE TITLE
Pause extruder or change filament problem

### ISSUE THREAD

**Issue by se3d** [makerbase-mks/MKS-SBASE#34]
Using a mks touch 3.2 display, the pause or change fillament when back (resume print),  the extruder motor freeze or goes to wrong direction.

**Comment by salcofago** [comment]
i had same problem

**Comment by pixel3design-hub** [comment]
to help you out, I need the TFT and SBASE configs.

**Comment by se3d** [comment]
**_TFT:_**

#mainboard firmware setting(marlin:1; repetier:2; smoothie:3)
>cfg_firmware_type:1

#machine setting (Normal:1; Delta:2)
>cfg_machine_type:1

#language (Simplified Chinese:1; traditional Chinese:2; English:3)
>cfg_language_type:3

#whether set machine auto-off after print finishes(auto-off:1; NO:0)
>cfg_print_finish_close_Machine:0

#pause position (-1 is invalid; Z-axis is relative position)
>cfg_XPOS:-1
>cfg_YPOS:-1
>cfg_ZADD:10

#extruder number(one:1; dual:2)
>cfg_sprayer_counter:1

#whether has heated bed(YES:1; NO: 0)
>cfg_custom_bed_flag:1

#the max target Temp of sprayer and heated bed
>cfg_max_sprayer_temperature:270
>cfg_max_hotbed_temperature:150

#the level signal of outage detection module PB1(low level:0; high level:1)
>cfg_PB0_PB1_Level:1

#wifi mode(AP:1; STA:2)
>cfg_wifi_mode:1

#wifi name and password
>cfg_wifi_ap_name:MKS_wifi
>cfg_wifi_key_code:makerbase

#Dynamic access IP
>cfg_ip_dhcp_flag:1

#IP/mask/gateway
>cfg_ip_address:192.168.3.100
>cfg_ip_mask:255.255.255.0
>cfg_ip_gate:192.168.3.1

#the color of screen background
>cfg_background_color:0x000000

#the color of title text
>cfg_title_color:0xFFFFFF

#the color of temperature,fan,(etc) background
>cfg_state_background_color:0x000000

#the color of temprature,fan,(etc) text
>cfg_state_text_color:0xFFFFFF

#the color of file button
>cfg_filename_background_color:0x000000

#the color of file text
>cfg_filename_color:0xFFFFFF

#the color of background in printing 
>cfg_printingstat_word_background_color:0x000000

#the color of text in printing status
>cfg_printingstat_word_color:0xFFFFFF

#3D effects setting (disable: 0; enable: 1)
>cfg_BUTTON_3D_effects:0

#the speed of filament replacing(mm/min)
>cfg_filament_change_speed:1200
#the length of filament replacing(mm)
>cfg_filament_change_step:5
#the min temperature of filament replacing
>cfg_filament_limit_temperature:175

#bed leveling setting(auto leveler:1; manual leveling:0)
>cfg_leveling_mode:0

#the coordinates of 4 point  on manual leveling
>cfg_point1:50,50
>cfg_point2:180,50
>cfg_point3:180,180
>cfg_point4:50,180

#the moving speed of leveling(mm/min)
>cfg_leveling_z_speed:1500
>cfg_leveling_xy_speed:3000

#user-defined function1 and 2.(whether display this button .  disable: 0; enable: 1)
>cfg_function_btn1_display:1
>cfg_function_btn2_display:1

#command of user-defined function
>function_btn1_cmd:M84;
>function_btn2_cmd:G28;G29;

#set number of  "More" button 
>moreitem_pic_cnt:0

#edit command for 1~7 "More" button,each command must be separated by semicolon ";"
>moreitem_button1_cmd:G28 X0;

>moreitem_button2_cmd:G28 X0;

>moreitem_button3_cmd:G28 Y0;

>moreitem_button4_cmd:G28 Y0;

>moreitem_button5_cmd:G28 Z0;

>moreitem_button6_cmd:G28 Z0;

>moreitem_button7_cmd:G28;

#how many "More" button show on screen interface
>morefunc_cnt:0

#command setting on button1~6
>morefunc1_cmd:G28;
>morefunc2_cmd:G28;
>morefunc3_cmd:G28;
>morefunc4_cmd:G28;
>morefunc5_cmd:G28;
>morefunc6_cmd:G28;

**_Board:_**

# NOTE Lines must not exceed 132 characters
# Robot module configurations : general handling of movement G-codes and slicing into moves




arm_solution.                                corexy                 # Possible values : cartesian, corexy, linear_delta, rotatable_cartesian, morgan


#CNC MODE
#grbl_mode    true
#soft_endstops.job_limit                      XZ


soft_endstop.enable   true               # enable soft endstops
soft_endstop.halt     false               # HALT when soft endstop triggered (safest) when set to false the entire move will just be ignored
soft-endstop.x_min                           0
soft-endstop.x_max                           379
soft-endstop.y_min                           0
soft-endstop.y_max                           259
soft-endstop.z_min                           0
soft-endstop.z_max                           279.9

default_feed_rate                            6000             # Default rate ( mm/minute ) for G1/G2/G3 moves
default_seek_rate                            6000             # Default rate ( mm/minute ) for G0 moves
mm_per_arc_segment                           0.5              # Arcs are cut into segments ( lines ), this is the length for
                                                              # these segments.  Smaller values mean more resolution,
                                                              # higher values mean faster computation
mm_per_line_segment                          5                # Lines can be cut into segments ( not usefull with cartesian
                                                              # coordinates robots ).

# Arm solution configuration : Cartesian robot. Translates mm positions into stepper positions
alpha_steps_per_mm                           100.0 #78.7402               # Steps per mm for alpha stepper
beta_steps_per_mm                            100.0 #78.7402               # Steps per mm for beta stepper
gamma_steps_per_mm                           2560             # Steps per mm for gamma stepper

# Planner module configuration : Look-ahead and acceleration configuration
planner_queue_size                           32               # DO NOT CHANGE THIS UNLESS YOU KNOW EXACTLY WHAT YOU ARE DOING
acceleration                                 15000             # Acceleration in mm/second/second.
z_acceleration                              800              # Acceleration for Z only moves in mm/s^2, 0 uses acceleration which is the default. DO NOT SET ON A DELTA
acceleration_ticks_per_second                1000             # Number of times per second the speed is updated
junction_deviation                           0.02             # Similar to the old "max_jerk", in millimeters,
                                                              # see https://github.com/grbl/grbl/blob/master/planner.c
                                                              # and https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.8
                                                              # Lower values mean being more careful, higher values means being
                                                              # faster and have more jerk
#z_junction_deviation                        0.0              # for Z only moves, -1 uses junction_deviation, zero disables junction_deviation on z moves DO NOT SET ON A DELTA
#minimum_planner_speed                       0.0              # sets the minimum planner speed in mm/sec





# Stepper module configuration
microseconds_per_step_pulse                  1                # Duration of step pulses to stepper drivers, in microseconds
base_stepping_frequency                      100000           # Base frequency for stepping, higher gives smoother movement

# Cartesian axis speed limits
x_axis_max_speed                             15000            # mm/min
y_axis_max_speed                             15000            # mm/min
z_axis_max_speed                             100             # mm/min

# Stepper module pins ( ports, and pin numbers, appending "!" to the number will invert a pin )
alpha_step_pin                               2.0              # Pin for alpha stepper step signal
alpha_dir_pin                                0.5              # Pin for alpha stepper direction
alpha_en_pin                                 0.4              # Pin for alpha enable pin
alpha_current                                1.4             # X stepper motor current
alpha_max_rate                               18000.0          # mm/min

beta_step_pin                                2.1              # Pin for beta stepper step signal
beta_dir_pin                                 0.11             # Pin for beta stepper direction
beta_en_pin                                  0.10             # Pin for beta enable
beta_current                                 1.4              # Y stepper motor current
beta_max_rate                                18000.0          # mm/min

gamma_step_pin                               2.2              # Pin for gamma stepper step signal
gamma_dir_pin                                0.20!             # Pin for gamma stepper direction
gamma_en_pin                                 0.19             # Pin for gamma enable
gamma_current                                1.60              # Z stepper motor current
gamma_max_rate                               50.0            # mm/min

# Serial communications configuration ( baud rate default to 9600 if undefined )
uart0.baud_rate                              115200           # Baud rate for the default hardware serial port
second_usb_serial_enable                     true            # This enables a second usb serial port (to have both pronterface
                                                              # and a terminal connected)
#leds_disable                                true             # disable using leds after config loaded
#play_led_disable                            true             # disable the play led
pause_button_enable                          true             # Pause button enable
#pause_button_pin                            2.12             # pause button pin. default is P2.12
#kill_button_enable                           false            # set to true to enable a kill button
#kill_button_pin                              2.12             # kill button pin. default is same as pause button 2.12 (2.11 is another good choice)
#msd_disable                                 false            # disable the MSD (USB SDCARD) when set to true (needs special binary)
#dfu_enable                                  false            # for linux developers, set to true to enable DFU

custom_menu.filament_change_c.enable               true                                                   #
custom_menu.filament_change_c.name                 Change Filament                                        #
custom_menu.filament_change_c.command              G91|G1_Z0.6_F12000|G90|G1_X0_Y0|G91|G1_Z-0.6|G90|M25   #

custom_menu.filament_change_r.enable               true              #
custom_menu.filament_change_r.name                 Resume            #
custom_menu.filament_change_r.command              M24               #

# Extruder module configuration
extruder.hotend.enable                          true             # Whether to activate the extruder module at all. All configuration is ignored if false
extruder.hotend.steps_per_mm                    150              # Steps per mm for extruder stepper
extruder.hotend.default_feed_rate               600              # Default rate ( mm/minute ) for moves where only the extruder moves
extruder.hotend.acceleration                    1000              # Acceleration for the stepper motor, as of 0.6, arbitrary ratio
extruder.hotend.max_speed                       300               # mm/s

extruder.hotend.step_pin                        2.3              # Pin for extruder step signal
extruder.hotend.dir_pin                         0.22!             # Pin for extruder dir signal
extruder.hotend.en_pin                          0.21             # Pin for extruder enable signal

# extruder offset
#extruder.hotend.x_offset                        0                # x offset from origin in mm
#extruder.hotend.y_offset                        0                # y offset from origin in mm
#extruder.hotend.z_offset                        0                # z offset from origin in mm

# firmware retract settings when using G10/G11, these are the defaults if not defined, must be defined for each extruder if not using the defaults
#extruder.hotend.retract_length                  3               # retract length in mm
#extruder.hotend.retract_feedrate                45              # retract feedrate in mm/sec
#extruder.hotend.retract_recover_length          0               # additional length for recover
#extruder.hotend.retract_recover_feedrate        8               # recover feedrate in mm/sec (should be less than retract feedrate)
#extruder.hotend.retract_zlift_length            0               # zlift on retract in mm, 0 disables
#extruder.hotend.retract_zlift_feedrate          6000            # zlift feedrate in mm/min (Note mm/min NOT mm/sec)

delta_current                                1.0              # First extruder stepper motor current

# Second extruder module configuration
#extruder.hotend2.enable                          true             # Whether to activate the extruder module at all. All configuration is ignored if false
#extruder.hotend2.steps_per_mm                    140              # Steps per mm for extruder stepper
#extruder.hotend2.default_feed_rate               600              # Default rate ( mm/minute ) for moves where only the extruder moves
#extruder.hotend2.acceleration                    500              # Acceleration for the stepper motor, as of 0.6, arbitrary ratio
#extruder.hotend2.max_speed                       50               # mm/s

#extruder.hotend2.step_pin                        2.8              # Pin for extruder step signal
#extruder.hotend2.dir_pin                         2.13             # Pin for extruder dir signal
#extruder.hotend2.en_pin                          4.29             # Pin for extruder enable signal

#extruder.hotend2.x_offset                        0                # x offset from origin in mm
#extruder.hotend2.y_offset                        25.0             # y offset from origin in mm
#extruder.hotend2.z_offset                        0                # z offset from origin in mm
#epsilon_current                              1.0              # Second extruder stepper motor current


# Laser module configuration
laser_module_enable                          false            # Whether to activate the laser module at all. All configuration is
                                                              # ignored if false.
#laser_module_pin                             2.5             # this pin will be PWMed to control the laser. Only P2.0 - P2.5, P1.18, P1.20, P1.21, P1.23, P1.24, P1.26, P3.25, P3.26
                                                              # can be used since laser requires hardware PWM
#laser_module_max_power                       0.8             # this is the maximum duty cycle that will be applied to the laser
#laser_module_tickle_power                    0.0             # this duty cycle will be used for travel moves to keep the laser
                                                              # active without actually burning
#laser_module_pwm_period                      20              # this sets the pwm frequency as the period in microseconds

# Hotend temperature control configuration
temperature_control.hotend.enable            true             # Whether to activate this ( "hotend" ) module at all.
                                                              # All configuration is ignored if false.
temperature_control.hotend.thermistor_pin    0.24             # Pin for the thermistor to read
temperature_control.hotend.heater_pin        2.7              # Pin that controls the heater, set to nc if a readonly thermistor is being defined   2.7
temperature_control.hotend.thermistor        RRRF100K       # see http://smoothieware.org/temperaturecontrol#toc5
temperature_control.hotend.beta             3960             # or set the beta value
temperature_control.hotend.set_m_code        104              #
temperature_control.hotend.set_and_wait_m_code 109            #
temperature_control.hotend.designator        T                #

temperature_control.hotend.p_factor         13.7             # permanently set the PID values after an auto pid
temperature_control.hotend.i_factor         0.097            #
temperature_control.hotend.d_factor         24               #

temperature_control.hotend.max_pwm          255               # max pwm, 64 is a good value if driving a 12v resistor with 24v.

# Hotend2 temperature control configuration
temperature_control.hotend2.enable            true             # Whether to activate this ( "hotend" ) module at all.
                                                              # All configuration is ignored if false.

temperature_control.hotend2.thermistor_pin    0.25             # Pin for the thermistor to read
temperature_control.hotend2.heater_pin        1.23             # Pin that controls the heater
temperature_control.hotend2.thermistor        RRRF100K        # see http://smoothieware.org/temperaturecontrol#toc5
temperature_control.hotend2.beta             4066             # or set the beta value
temperature_control.hotend2.set_m_code        884              #
temperature_control.hotend2.set_and_wait_m_code 889            #
temperature_control.hotend2.designator        T1               #

temperature_control.hotend2.p_factor          13.7           # permanently set the PID values after an auto pid
temperature_control.hotend2.i_factor          0.097          #
temperature_control.hotend2.d_factor          24             #

temperature_control.hotend2.max_pwm          64               # max pwm, 64 is a good value if driving a 12v resistor with 24v.

temperature_control.bed.enable               true             #
temperature_control.bed.thermistor_pin       0.23             #
temperature_control.bed.heater_pin           2.5              #  2.5
temperature_control.bed.thermistor           RRRF100K    # see http://smoothieware.org/temperaturecontrol#toc5
temperature_control.bed.beta                3960             # or set the beta value
temperature_control.bed.pwm_frequency        20              #for the SSR Relay
temperature_control.bed.set_m_code           140              #
temperature_control.bed.set_and_wait_m_code  190              #
temperature_control.bed.designator           B                #
temperature_control.bed.bang_bang            true           # set to true to use bang bang control rather than PID
temperature_control.bed.hysteresis           2.0             # set to the temperature in degrees C to use as hysteresis
                                                              # when using bang bang

# Switch module for fan control
switch.fan.enable                            true             #
switch.fan.input_on_command                  M106             #
switch.fan.input_off_command                 M107             #
switch.fan.output_pin                        2.4              #
switch.fan.output_type                       pwm              # pwm output settable with S parameter in the input_on_comand
switch.fan.max_pwm                           255              # set max pwm for the pin default is 255

#switch.misc.enable                           true             #
#switch.misc.input_on_command                 M42              #
#switch.misc.input_off_command                M43              #
#switch.misc.output_pin                       2.4              #
#switch.misc.output_type                      digital          # just an on or off pin

# automatically toggle a switch at a specified temperature. Different ones of these may be defined to monitor different temperatures and switch different swithxes
# useful to turn on a fan or water pump to cool the hotend
temperatureswitch.hotend.enable	            true              #
temperatureswitch.hotend.designator          T                # first character of the temperature control designator to use as the temperature sensor to monitor
temperatureswitch.hotend.switch              misc             # select which switch to use, matches the name of the defined switch
#temperatureswitch.hotend.threshold_temp      60.0            # temperature to turn on (if rising) or off the switch
temperatureswitch.hotend.heatup_poll         15               # poll heatup at 15 sec intervals
temperatureswitch.hotend.cooldown_poll       60               # poll cooldown at 60 sec intervals
#temperature_control.module_name.max_temp      290            #max temperature for hotted - Desligar para o MODO CNC OPERAR
#temperature_control.module_name.runaway_heating_timeout      120 # max is 2040 seconds
#temperature_control.module_name.runaway_range      20 # Max setting is 63°C
# Switch module for spindle control
#switch.spindle.enable                        false           #

# Endstops
endstops_enable                              true             # the endstop module is enabled by default and can be disabled here
corexy_homing                               true             # set to true if homing on a hbit or corexy
alpha_min_endstop                            1.24^!           # add a ! to invert if endstop is NO connected to ground
alpha_max_endstop                            nc #1.25^        # NOTE set to nc if this is not installed
alpha_homing_direction                       home_to_min      # or set to home_to_max and set alpha_max
alpha_min                                    0                # this gets loaded after homing when home_to_min is set
alpha_max                                    380              # this gets loaded after homing when home_to_max is set
beta_min_endstop                             1.26^!           #
beta_max_endstop                             nc #1.27^        #
beta_homing_direction                        home_to_min      #
beta_min                                     0                #
beta_max                                     280              #
gamma_min_endstop                            nc #1.28^!       #
gamma_max_endstop                            1.29^!           #
gamma_homing_direction                       home_to_max      #
gamma_min                                    0                #
gamma_max                                    279.90           #Z Height


# optional order in which axis will home, default is they all home at the same time,
# if this is set it will force each axis to home one at a time in the specified order
#homing_order                                 XYZ              # x axis followed by y then z last

# optional enable limit switches, actions will stop if any enabled limit switch is triggered
alpha_limit_enable                          false              # set to true to enable X min and max limit switches
beta_limit_enable                           false              # set to true to enable Y min and max limit switches
gamma_limit_enable                          false              # set to true to enable Z min and max limit switches

alpha_fast_homing_rate_mm_s                  100               # feedrates in mm/second
beta_fast_homing_rate_mm_s                   100               # "
gamma_fast_homing_rate_mm_s                  1                 # "
alpha_slow_homing_rate_mm_s                  50                # "
beta_slow_homing_rate_mm_s                   50                # "
gamma_slow_homing_rate_mm_s                  1                 # "

alpha_homing_retract_mm                      1                 # distance in mm
beta_homing_retract_mm                       1                 # "
gamma_homing_retract_mm                      1                 # "

#endstop_debounce_count                       100              # uncomment if you get noise on your endstops, default is 100

# optional Z probe
zprobe.enable                                true              # set to true to enable a zprobe
zprobe.probe_pin                             1.28!^            # pin probe is attached to if NC remove the !
zprobe.slow_feedrate                         5                 # mm/sec probe feed rate
#zprobe.debounce_count                       100               # set if noisy
zprobe.fast_feedrate                         100               # move feedrate mm/sec
zprobe.probe_height                          5                 # how much above bed to start probe
#gamma_min_endstop                           nc                # normally 1.28. Change to nc to prevent conflict,

# associated with zprobe the leveling strategy to use
#leveling-strategy.three-point-leveling.enable         true        # a leveling strategy that probes three points to define a plane and keeps the Z parallel to that plane
#leveling-strategy.three-point-leveling.point1         100.0,0.0   # the first probe point (x,y) optional may be defined with M557
#leveling-strategy.three-point-leveling.point2         200.0,200.0 # the second probe point (x,y)
#leveling-strategy.three-point-leveling.point3         0.0,200.0   # the third probe point (x,y)
#leveling-strategy.three-point-leveling.home_first     true        # home the XY axis before probing
#leveling-strategy.three-point-leveling.tolerance      0.03        # the probe tolerance in mm, anything less that this will be ignored, default is 0.03mm
#leveling-strategy.three-point-leveling.probe_offsets  0,0,0       # the probe offsets from nozzle, must be x,y,z, default is no offset
#leveling-strategy.three-point-leveling.save_plane     false       # set to true to allow the bed plane to be saved with M500 default is false

# Panel# config settings
panel.enable                          true              # set to true to enable the panel code
panel.lcd                             reprap_discount_glcd     # set type of panel
panel.spi_channel                     0                 # spi channel to use  ; GLCD EXP1 Pins 3,5 (MOSI, SCLK)
panel.spi_cs_pin                      0.16              # spi chip select     ; GLCD EXP1 Pin 4
panel.encoder_a_pin                   3.25!^            # encoder pin         ; GLCD EXP2 Pin 3
panel.encoder_b_pin                   3.26!^            # encoder pin         ; GLCD EXP2 Pin 5
panel.click_button_pin                1.30!^            # click button        ; GLCD EXP1 Pin 2
panel.buzz_pin                        1.31              # pin for buzzer      ; GLCD EXP1 Pin 1
panel.back_button_pin                 2.11!^            # 2.11 menu back      ; GLCD EXP2 Pin 8
# setup for external sd card on the GLCD which uses the onboard sdcard SPI port
panel.external_sd                     false              # set to true if there is an extrernal sdcard on the panel
panel.external_sd.spi_channel         1                 # set spi channel the sdcard is on
panel.external_sd.spi_cs_pin          0.28              # set spi chip select for the sdcard (or any spare pin)
panel.external_sd.sdcd_pin            0.27!^            # sd detect signal (set to nc if no sdcard detect) (or any spare pin)


# pins used with other panels
#panel.up_button_pin                         0.1!              # up button if used
#panel.down_button_pin                       0.0!              # down button if used
#panel.click_button_pin                      0.18!             # click button if used

panel.menu_offset                            1                 # some panels will need 1 here

panel.alpha_jog_feedrate                     6000              # x jogging feedrate in mm/min
panel.beta_jog_feedrate                      6000              # y jogging feedrate in mm/min
panel.gamma_jog_feedrate                     5000               # z jogging feedrate in mm/min

panel.hotend_temperature                     185               # temp to set hotend when preheat is selected
panel.bed_temperature                        80                # temp to set bed when preheat is selected

# Example of a custom menu entry, which will show up in the Custom entry.
# NOTE _ gets converted to space in the menu and commands, | is used to separate multiple commands
custom_menu.power_on.enable                false              #true
custom_menu.power_on.name                  Power_on          #
custom_menu.power_on.command               M80               #

custom_menu.power_off.enable               false              #true
custom_menu.power_off.name                 Power_off         #
custom_menu.power_off.command              M81               #

# Only needed on a smoothieboard
currentcontrol_module_enable                  true             #


return_error_on_unhandled_gcode              true            #false

# network settings
network.enable                               true             # enable the ethernet network services
network.webserver.enable                     true             # enable the webserver
network.telnet.enable                        true             # enable the telnet server
network.plan9.enable                         true             # enable the plan9 network filesystem
network.ip_address  auto                     # use dhcp to get IP address
network.ip_address                           192.168.1.254    # the IP address
network.ip_mask                              255.255.255.0    # the ip mask
network.ip_gateway                           192.168.1.1      # the gateway address
network.hostname   King_Core                 # optionally set this hostname for dhcp

**Comment by se3d** [comment]
[config.txt](https://github.com/makerbase-mks/MKS-SBASE/files/1237563/config.txt)
[config.txt](https://github.com/makerbase-mks/MKS-SBASE/files/1237565/config.txt)

**Comment by pixel3design-hub** [comment]
X and Y Pos could not be -1, is invalid...
I got mine with X = 0 and Y = 250 (this must be relative to your machine bed dimensions)
Config Firmware must be set to 3, you are using a Smoothie knockoff

**Comment by se3d** [comment]
Ok, I will try and post results. Thanks

**Comment by se3d** [comment]
Ok. I got my code with your recommendations, but the same problem . wrong direction of extrusion, Z without touch the nozzle and no filament extrusion.

**Comment by michail58** [comment]
У МЕНЯ ТАЖЕ ПРОБЛЕМА

**Comment by pixel3design-hub** [comment]
-1 means "no movement"
IMHO, the swap between the G91 and G90 without resetting the filament position is the main cause.
I've been harassed by the same behavior some time ago.
Marlin is doing it the same way.
`custom_menu.filament_change_c.enable               true                                                   #
custom_menu.filament_change_c.name                 Change Filament                                        #
custom_menu.filament_change_c.command              G91|G1_Z0.6_F12000|G90|G1_X0_Y0|G91|G1_Z-0.6|G90|M25   #

custom_menu.filament_change_r.enable               true              #
custom_menu.filament_change_r.name                 Resume            #
custom_menu.filament_change_r.command              M24               #`

last row cannot be just an M24. You HAVE to reset the filament lenght with
`G91|M92 E0.0|G90|M24`
Try it and let us know.
Cheers
