### ISSUE TITLE
Board is neither updating firmware nor responding on USB

### ISSUE THREAD

**Issue by mtavenrath** [makerbase-mks/MKS-SBASE#36]
What's a good way to get diagnostics from the board?

When powering the board with a USB card two files, firmware.bin and config and powering the board on D7 turns on. After around a minute the other 4 LEDs start to glim. The board also doesn't show up as USB device on a PC and doesn't react to any commands from the MKS TFT.

Looking at smoothieware.org one might want to try to update the bootloader, but it's not clear how to enter the rescue mode since there's no information which pins would have the RS232 pins for the bootloader flash and where the Bootloader (ISP) pin would be.

**Comment by makerbase-mks** [comment]
After the board update firmware ,name of firmware.bin will rename the FIRMWARE.CUR. 
If you want to update the bootloader, you can update it in the J2 interface.

**Comment by mtavenrath** [comment]
@makerbase-mks The board update through the sd card does not work. D7 stays green and the file never gets renamed.

Where can I can find a manual on how to flash the board through the J2 interface?

**Comment by MD3DDelta** [comment]
Hi , in my case the mks tft works perfect ,when the board has 12volt powered on .
when power is off it has the problem what you have . 
format the sd-card and start over again , sometimes there are trouble with some sd-cards ,
use an small one . the new cards are sometimes to fast, the board works then halfway .
i use 8GB 10mb /s, that works .
greetz mike

**Comment by pixel3design-hub** [comment]
https://github.com/pixel3design-hub/MKS-SBASE-FULL-DOCUMENTED

I made a fork and reuploaded the schematics. I hope it could help.

**Comment by Filcanna** [comment]
It would be very kind to have clear indication of the pins to which you attach the programmer ...
