### ISSUE TITLE
How do I hook up a BLTouch 

### ISSUE THREAD

**Issue by JimSVMI83** [makerbase-mks/MKS-SBASE#4]
Trying to hook up a BLTouch to an MKS-Sbase can you help me

**Comment by TGMods** [comment]
Have a look at [https://plus.google.com/113792662927481823969/posts/J1PDbrmvcU3]

**Comment by elvisior** [comment]
The page linked to above returns a 404 not found error.

Slightly useful link... 

http://smoothieware.org/forum/t-1760423/bltouch-support
