### ISSUE TITLE
No power to Bedheater?

### ISSUE THREAD

**Issue by undertowx** [makerbase-mks/MKS-SBASE#44]
So I now have Extruder heater and thermistor working but no output power to the Hotbed?

**Comment by pixel3design-hub** [comment]
Take off all' comments. Over 136 chars per line is not allowed by the firmware.

**Comment by pixel3design-hub** [comment]
TH3 is not a designator. T3 is, unless you have modified profiles in slicing software and changed the designator

**Comment by undertowx** [comment]
Thanks for the insight. I will try both.

**Comment by undertowx** [comment]
No luck with the heatbed, got the hotend working.
this is my heatbed config? whats wrong?
##Heated bed temperature control configuration
temperature_control.bed.enable               TRUE             # Whether to activate this ( "hotend" ) module at all.
temperature_control.bed.thermistor_pin       0.23             # TH1 Pin for the thermistor to read
temperature_control.bed.heater_pin           2.5              # Pin that controls the heater
#temperature_control.bed.thermistor           Honeywell100K	  # See http://smoothieware.org/temperaturecontrol#thermistor
temperature_control.bed.beta                 4066             # Or set the beta value
temperature_control.bed.set_m_code           140              # M-code to set the temperature for this module
temperature_control.bed.set_and_wait_m_code  190              # M-code to set-and-wait for this module
temperature_control.bed.designator           B                # Designator letter for this module

# Bang-bang ( simplified ) control
# See http://smoothieware.org/temperaturecontrol#bang-bang


temperature_control.bed.bang_bang           true           # Set to true to use bang bang control rather than PID
temperature_control.bed.hysteresis          2.0              # Set to the temperature in degrees C to use as hysteresis

**Comment by undertowx** [comment]
hot end working, but not the heatbed? here is the config.

##Heated bed temperature control configuration
temperature_control.bed.enable               TRUE             # Whether to activate this ( "hotend" ) module at all.
temperature_control.bed.thermistor_pin       0.23             # TH1 Pin for the thermistor to read
temperature_control.bed.heater_pin           2.5              # Pin that controls the heater
#temperature_control.bed.thermistor           Honeywell100K	  # See http://smoothieware.org/temperaturecontrol#thermistor
temperature_control.bed.beta                 4066             # Or set the beta value
temperature_control.bed.set_m_code           140              # M-code to set the temperature for this module
temperature_control.bed.set_and_wait_m_code  190              # M-code to set-and-wait for this module
temperature_control.bed.designator           B                # Designator letter for this module

# Bang-bang ( simplified ) control
# See http://smoothieware.org/temperaturecontrol#bang-bang


temperature_control.bed.bang_bang           true           # Set to true to use bang bang control rather than PID
temperature_control.bed.hysteresis          2.0              # Set to the temperature in degrees C to use as hysteresis

**Comment by undertowx** [comment]
hot end working, but not the heatbed? here is the config.

##Heated bed temperature control configuration
temperature_control.bed.enable               TRUE             
temperature_control.bed.thermistor_pin       0.23             
temperature_control.bed.heater_pin           2.5              
#temperature_control.bed.thermistor           Honeywell100K	  
temperature_control.bed.beta                 4066             
temperature_control.bed.set_m_code           140             
temperature_control.bed.set_and_wait_m_code  190              
temperature_control.bed.designator           B                
# Bang-bang ( simplified ) control
# See http://smoothieware.org/temperaturecontrol#bang-bang


temperature_control.bed.bang_bang           true           
temperature_control.bed.hysteresis          2.0

**Comment by pixel3design-hub** [comment]
#temperature_control.bed.thermistor Honeywell100K

Take off the #

**Comment by undertowx** [comment]
still not sending any power to it!
