### ISSUE TITLE
Interrupt enabled GPIO pins on MKS-SBASE

### ISSUE THREAD

**Issue by dojo2017** [makerbase-mks/MKS-SBASE#49]
Does the MKS-SBASE v1.3 have interrupt enabled GPIO pins available? If so, where are they located on the board?

**Comment by oddstr13** [comment]
Pinouts can be found here: https://github.com/pixel3design-hub/MKS-SBASE-FULL-DOCUMENTED/blob/master/MKS%20SBASE%20SCH_V12.pdf

Pin functions can be found in the µC datasheet at https://www.nxp.com/docs/en/data-sheet/LPC1769_68_67_66_65_64_63.pdf

From section 8.7.2:
> Any pin on Port 0 and Port 2 (total of 42 pins) regardless of the selected function, can be programmed to generate an interrupt on a rising edge, a falling edge, or both.

By my count, that would give you 15 interrupt capable pins, spread over the connectors `J7`, `J8`, `EXP1`, `EXP2` and `AUX-1`. Most of the pins in use for specific functions such as stepper axes and heater outputs are also from those two ports, but those are generally not available as they are in use.

Do note that I haven't actually tested this myself.
