### ISSUE TITLE
Specification for the MKS-BASE v1.3

### ISSUE THREAD

**Issue by WD24** [makerbase-mks/MKS-SBASE#55]
Where can I find the spec's for this board?
How much curent can each FET take on this board etc?

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-SBASE/blob/master/English/MKS-SBASE%20DataSheet.pdf

**Comment by laris** [comment]
That is SBASE, not BASE v1.3
I'm also searching the MKS BASE v1.3 version DS.
the MKS BASE DS is v1.5.
Did makebase delete or didn't publish v1.3 DS?
