### ISSUE TITLE
How to print from micro SD card?

### ISSUE THREAD

**Issue by HugoW1975** [makerbase-mks/MKS-SBASE#56]
Hi,

I have the MKS SBase V1.3 and it's TFT32 screen working. The machine is putting out nice prints. I would really like to print from the micro SD card in the SBase, because I could then hook the SBase up to the LAN and convey the files from the PC to the printer over the network.

Please advise,
Cheers,

Hugo

**Comment by HugoW1975** [comment]
Not sure why I closed this, I still want to print from the SD card in the SBase, not in the TFT slot, as that is probably an issue contributing to my problems.

Thanks for advice,

Hugo

**Comment by BurtisaWord** [comment]
Command is:
M32 XYZ.gcode

http://smoothieware.org/supported-g-codes
