### ISSUE TITLE
Motors vibrating but not turning eratically

### ISSUE THREAD

**Issue by rdrand** [makerbase-mks/MKS-SBASE#57]
New installation on a Prusa I3. The problem happens on X and Y, Z seems OK. I have swapped wiring, tried a new stepper, removed some stress on the physical setup (it was a little stiff on the belts). I've tried adjusting the current between .5A to 1.5A and all to no avail. The steppers are Nema 17s spec'd at 1.2A.

Thoughts?

**Comment by rdrand** [comment]
OK, I feel sufficiently stupid. It never (ever) occurred to me that given the same connector that the pair could be wired either 2211 or 1212. Reverse two and voila life is good.

**Comment by rmhorwitz** [comment]
Thank you for this lesson.
