### ISSUE TITLE
Where is function2 button on 3.0.1 firmare?

### ISSUE THREAD

**Issue by Tagir-Gilyazov** [makerbase-mks/MKS-SBASE#61]
I try all version (Classic, Retro, Simple) there is not
`>cfg_function_btn2_display:1
in mks_config.txt. I insert lines by myself. And add
`>function_btn2_cmd:M84;
but nothing happens. File bmp_function2.bin in all yours firmwares.

**Comment by makerbase-mks** [comment]
Version 3.1 firmware has been removed "function2 button".
