### ISSUE TITLE
2nd home request does not home alpha servo on delta mode

### ISSUE THREAD

**Issue by rmhorwitz** [makerbase-mks/MKS-SBASE#65]
Folks I have an interesting problem.  When I initially home my delta printer (after power-on) all three servos act normally and they all home accordingly.  However, if I attempt to home it again, the Alpha servo increments downward in the opposite direction while the remaining servos home accordingly.  I loaded the latest and greatest firmware from MKS (on this website), and now when I initiated a second home command both alpha and beta servo move slightly in the wrong direction while the gamma homed as expected.  Hence, the new firmware made it worse.  Config servo stuff below (other stuff omitted):
arm_solution                                 linear_delta     # delta
#---------------------------------------------------------------------------
#Basic Parameters
# based on 1/32 microstepping:
alpha_steps_per_mm                           160              # Steps per mm for alpha stepper
beta_steps_per_mm                            160              # Steps per mm for beta stepper
gamma_steps_per_mm                           160              # Steps per mm for gamma stepper
extruder.hotend.steps_per_mm                 160              # Steps per mm for extruder stepper

arm_length                                   219           # this is the length of an arm from hinge to hinge
arm_radius                                   168.5           # this is the horizontal distance from hinge to hinge
                                                             # when the effector is centered
gamma_max                                    289             # Print Height

alpha_current                     1.0                        # X stepper motor current
beta_current                      1.0                        # Y stepper motor current
gamma_current                     1.0                        # Z stepper motor current
delta_current                     1.0                        # E0 stepper motor current

alpha_dir_pin                     0.5                       # Pin for alpha stepper direction
beta_dir_pin                      0.11                      # Pin for beta stepper direction
gamma_dir_pin                     0.20                      # Pin for gamma stepper direction
extruder.hotend.dir_pin           0.22                      # Pin for extruder stepper direction
#servo step and enable pins
alpha_step_pin                               2.0              # Pin for alpha stepper step signal
alpha_en_pin                                 0.4              # Pin for alpha enable pin
beta_step_pin                                2.1              # Pin for beta stepper step signal
beta_en_pin                                  0.10             # Pin for beta enable
gamma_step_pin                               2.2              # Pin for gamma stepper step signal
gamma_en_pin                                 0.19             # Pin for gamma enable
default_feed_rate                            18000            # Default rate ( mm/minute ) for G1/G2/G3 moves
default_seek_rate                            4000            # Default rate ( mm/minute ) for G0 moves
acceleration                                 3000            # Acceleration in mm/second/second.
junction_deviation                           0.05            # Similar to the old "max_jerk", in millimeters,
                                                             # see https://github.com/grbl/grbl/blob/master/planner.c#L409
                                                             # and https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.8
                                                             # Lower values mean being more careful, higher values means being
                                                             # faster and have more jerk

x_axis_max_speed                             30000            # mm/min
y_axis_max_speed                             30000            # mm/min
z_axis_max_speed                             30000            # mm/min

alpha_max_rate                               30000.0          # mm/min
beta_max_rate                                30000.0          # mm/min
gamma_max_rate                               30000.0          # mm/min

If anyone has any clue to what is going on, I would be forever grateful.

Thanks,

Rick

**Comment by rmhorwitz** [comment]
Ok, I found something interesting.  Appears that my opto-switches are working marginally on the Alpha limit port.  perhaps no logic pull downs? I changed ports and it is now working.  Thanks for all your enthusiastic support.

**Comment by pixel3design-hub** [comment]
> I loaded the latest and greatest firmware from MKS (on this website)

**NOT. There's no MKS firmware whatsoever. MKS uses Smoothieware Firmware and giving no support at all to the project.**
You'll be quite lucky if you find an answer from MKS peoples, most of the answering came from the community and me. I'm not from Smoothieware nor MKS. I own the two boards. Period.
**MKS stole work from Smoothieware without even giving any thanks or credit. They stole other peoples work. _THEY STOLE IT._**

Don't be so surprised if no one answer your question. You don't even paste all your config. And surely no help from MKS peoples will come in, anyway.

Cheers
