### ISSUE TITLE
Dual Y-Axis with external driver LV8727

### ISSUE THREAD

**Issue by bertrandletot** [makerbase-mks/MKS-SBASE#67]
Hi, 

On a cnc machine used with the sbase v1.3 i need 2 y axis.
Stepper motor Nema23 270 oz 3A  is too big for the internal driver, so i have 2 external driver LV8727 from mks.
I try to do that : http://smoothieware.org/cnc-mill-guide#doubling-stepper-motor-drivers
I'm using the last firmware [from smoothieware](https://github.com/Smoothieware/Smoothieware/tree/edge/FirmwareBin)
Can i just link 2 external driver LV8727 to the pinout jc_m3 ?

Thanks,

Bertrand

**Comment by ghost** [comment]
I think this is an hardware related question.
You should ask on the MKS project repository.

**Comment by bertrandletot** [comment]
Hi pixel3Design, 
But I thought I was on the MKS project repository.

Bertrand

**Comment by pixel3design-hub** [comment]
So sorry... My bad... Too many repos to look for...
And yes you can indeed.
Connect GND, EN, STEP, DIR pins respectively and should work
