### ISSUE TITLE
Does not support multiple power supplies

### ISSUE THREAD

**Issue by lordofhyphens** [makerbase-mks/MKS-SBASE#7]
The MOSFETs all appear to be between the heater/fan terminals and VCC, which removes the ability to bypass the main power input so that a second power source may be used (24V heater, 12V stepper motors, or 12V fans and 24V stepper drivers). 

Most other control boards put the MOSFETs on the GND path instead.

**Comment by makerbase-mks** [comment]
yes mks sbase only support one power supplies.

**Comment by evgs** [comment]
All mosfets on the SBASE are N-channel, sitting on the ground path. So board may work with both 12V and 24V if load + terminal will be connected to appropriate power source directly. Also it may be nessesary to unsolder some on-board LEDS, if board is powered 12V and load is 24V (else leds will be reverse-biased by 12V)

**Comment by evgs** [comment]
@lordofhyphens you may browse trough git history and dig out board sch ;)
