### ISSUE TITLE
no power from E1 pinnout?

### ISSUE THREAD

**Issue by undertowx** [makerbase-mks/MKS-SBASE#71]
everything was fine, print lifted from bed and looks like a bunch of plastic blobbed around nozzle, now I have no power coming from the P2.7-E1 port on the board?
I guess I could move to E-2 P2,6 but would lose my extra fan as well?
Help?

**Comment by pixel3design-hub** [comment]
Can you please paste your config?

**Comment by undertowx** [comment]
# Smoothieboard configuration file, see http://smoothieware.org/configuring-smoothie
# NOTE Lines must not exceed 132 characters, and '#' characters mean what follows is ignored
## Robot module configurations : general handling of movement G-codes and slicing into moves


################ARH DELTA PRINTER##################################

# Basic motion configuration
default_feed_rate                            18000            
default_seek_rate                            18000            
mm_per_arc_segment                           0.0             
#mm_per_line_segment                         5                
mm_max_arc_error                             0.01             
                                                              
                                                              
delta_segments_per_second                    100              
                                                              

# Arm solution configuration : Cartesian robot. Translates mm positions into stepper positions
# See http://smoothieware.org/stepper-motors
alpha_steps_per_mm                           160              
beta_steps_per_mm                            160              
gamma_steps_per_mm                           160              

# Delta configuration
# See http://smoothieware.org/delta
arm_solution                                 linear_delta     
arm_length                                   405.156          
arm_radius                                   180.840            

# Planner module configuration : Look-ahead and acceleration configuration
# See http://smoothieware.org/motion-control
acceleration                                 3000             
#z_acceleration                              0                
junction_deviation                           0.05             
#z_junction_deviation                        0.0              

# Cartesian axis speed limits
x_axis_max_speed                             30000            
y_axis_max_speed                             30000            
z_axis_max_speed                             30000            

# Stepper module configuration 
# Pins are defined as  ports, and pin numbers, appending "!" to the number will invert a pin

alpha_step_pin                               2.0              
alpha_dir_pin                                0.5!              
alpha_en_pin                                 0.4              
alpha_current                                1.8
alpha_max_rate                               30000.0          

beta_step_pin                                2.1              
beta_dir_pin                                 0.11!             
beta_en_pin                                  0.10             
beta_current                                 1.8
beta_max_rate                                30000.0          

gamma_step_pin                               2.2              
gamma_dir_pin                                0.20!             
gamma_en_pin                                 0.19             
gamma_current                                1.8
gamma_max_rate                               30000.0          

## Extruder module configuration
# See http://smoothieware.org/extruder
extruder.hotend.enable                          true          
extruder.hotend.steps_per_mm                    190        
extruder.hotend.default_feed_rate               600           
extruder.hotend.acceleration                    500           
extruder.hotend.max_speed                       50            

extruder.hotend.step_pin                        2.3           
extruder.hotend.dir_pin                         0.22          
extruder.hotend.en_pin                          0.21          

# Extruder offset
#extruder.hotend.x_offset                        0            
#extruder.hotend.y_offset                        0            
#extruder.hotend.z_offset                        0            

# Firmware retract settings when using G10/G11, 
#extruder.hotend.retract_length                  3            
#extruder.hotend.retract_feedrate                45           
#extruder.hotend.retract_recover_length          0            
#extruder.hotend.retract_recover_feedrate        8            
#extruder.hotend.retract_zlift_length            0            
#extruder.hotend.retract_zlift_feedrate          6000         

delta_current                                    1.7          

# Second extruder module configuration
#extruder.hotend2.enable                         false         
#extruder.hotend2.steps_per_mm                   140          
#extruder.hotend2.default_feed_rate              600          
#extruder.hotend2.acceleration                   500          
#extruder.hotend2.max_speed                      50           

#extruder.hotend2.step_pin                       2.8          
#extruder.hotend2.dir_pin                        2.13         
#extruder.hotend2.en_pin                         4.29         

#extruder.hotend2.x_offset                       0            
#extruder.hotend2.y_offset                       25.0         
#extruder.hotend2.z_offset                       0            

#epsilon_current                                 1.5          

## Temperature control configuration
# See http://smoothieware.org/temperaturecontrol

# First hotend configuration
temperature_control.hotend.enable            true             
temperature_control.hotend.thermistor_pin    0.23             
temperature_control.hotend.heater_pin        2.7              
#temperature_control.hotend.thermistor       HT100K          
temperature_control.hotend.beta              3950              
temperature_control.hotend.set_m_code        104              
temperature_control.hotend.set_and_wait_m_code 109            
temperature_control.hotend.designator        t                
temperature_control.hotend.max_temp         300               
temperature_control.hotend.min_temp         20                

# Safety control is enabled by default and can be overidden here, 
# See http://smoothieware.org/temperaturecontrol#runaway
temperature_control.hotend.runaway_heating_timeout      900  
temperature_control.hotend.runaway_cooling_timeout        0  
temperature_control.hotend.runaway_range                20   

# PID configuration 
# See http://smoothieware.org/temperaturecontrol#pid
temperature_control.hotend.p_factor         31.8
temperature_control.hotend.i_factor         2.156
temperature_control.hotend.d_factor         101               

temperature_control.hotend.max_pwm          255              

##Heated bed temperature control configuration
temperature_control.bed.enable               true             
temperature_control.bed.thermistor_pin       0.24             
temperature_control.bed.heater_pin           2.5              
temperature_control.bed.thermistor          HT100K	        
temperature_control.bed.beta                 3950             
temperature_control.bed.set_m_code           140              
temperature_control.bed.set_and_wait_m_code  190              
temperature_control.bed.designator           b                

# Bang-bang ( simplified ) control
# See http://smoothieware.org/temperaturecontrol#bang-bang


temperature_control.bed.bang_bang           true           
temperature_control.bed.hysteresis          2.0              

## Switch modules
# See http://smoothieware.org/switch

# Switch module for fan control
switch.fan.enable                            true             
switch.fan.input_on_command                  M42             
switch.fan.input_off_command                 M43             
switch.fan.output_pin                        2.6              
switch.fan.output_type                       pwm              
#switch.fan.max_pwm                          255              

 switch.misc.enable                          true             
 switch.misc.input_on_command                M106              
 switch.misc.input_off_command               M107              
 switch.misc.output_pin                      2.4              
 switch.misc.output_type                     digital          

## Temperatureswitch
# See http://smoothieware.org/temperatureswitch
# Automatically toggle a switch at a specified temperature. 
# Useful to turn on a fan or water pump to cool the hotend
 temperatureswitch.hotend.enable              true            
 temperatureswitch.hotend.designator          b               
 temperatureswitch.hotend.switch              misc            
 temperatureswitch.hotend.threshold_temp      50.0            
 temperatureswitch.hotend.heatup_poll         15              
 temperatureswitch.hotend.cooldown_poll       60              

## Endstops
# See http://smoothieware.org/endstops
endstops_enable                              true            
delta_homing                                 true             
alpha_min_endstop                            nc               
alpha_max_endstop                            1.25^           
alpha_homing_direction                       home_to_max      
alpha_max                                    0                
beta_min_endstop                             nc               
beta_max_endstop                             1.27^           
beta_homing_direction                        home_to_max      
beta_max                                     0                
gamma_min_endstop                            nc               
gamma_max_endstop                            1.29^           
gamma_homing_direction                       home_to_max      
gamma_max                                    259.95

alpha_max_travel                             1000             
beta_max_travel                              1000             
gamma_max_travel                             1000             


alpha_fast_homing_rate_mm_s                  100              
alpha_slow_homing_rate_mm_s                  20               
beta_fast_homing_rate_mm_s                   100              
beta_slow_homing_rate_mm_s                   20               
gamma_fast_homing_rate_mm_s                  100              
gamma_slow_homing_rate_mm_s                  20               

alpha_homing_retract_mm                      5                
beta_homing_retract_mm                       5                
gamma_homing_retract_mm                      5                

# Endstop debouncing options
#endstop_debounce_count                       100              
#endstop_debounce_ms                          1                

# Endstop trim options
alpha_trim                                    0                
beta_trim                                     0                
gamma_trim                                    0                

# End of endstop config

#panel config
panel.enable true       
#--------------------------------------------------------------------
#########  Printer type setting  ##################################

#mainboard firmware setting(marlin:1; repetier:2; smoothie:3)
>cfg_firmware_type:3

#machine setting (Normal:1; Delta:2)
>cfg_machine_type:2

#baud rate (9600:1; 57600:2; 115200:3; 250000:4)
>cfg_baud_rate:3

#multi-language(enable:1, disable:0)
>cfg_multiple_language:0

#languages setting
#(simplified Chinese:1; traditional Chinese:2; English:3; Russian:4; Spanish:5). This configuration is valid when "cfg_multiple_language" is disabled.
>cfg_language_type:3

#extruder number(one:1; dual:2)
>cfg_sprayer_counter:1

#enable heated bed(yes:1; no: 0)
>cfg_custom_bed_flag:1

#the max target temp of extruder and heated bed
>cfg_max_sprayer_temperature:270
>cfg_max_hotbed_temperature:150

#pause position (-1 is invalid; Z-axis is relative position)
>cfg_XPOS:-1
>cfg_YPOS:-1
>cfg_ZADD:10

#-----------------------------------------------------------------------
#########  Advanced Function Option  ##################################

#enable UPS?(yes:1; no:0)
>cfg_have_ups_device:0

#enable power detecting module(mks 220det:1; mks pwc:0)
>cfg_insert_det_module:0

#enable auto off after print finish function (no:0; Yes:1?
>cfg_print_finish_close_Machine:0

#set PB0 signal when use it for sencond nozzle (high level:1; low level:0)
>cfg_PB0_trigger_Level:0

#set PB1 signal (high level:1; low level:0)
>cfg_PB1_trigger_Level:0

#set error range of Z-axis on breakpoints recovery 
>cfg_breakpoint_z_error:0.2

#---------------------------------------------------------------------------

#########  Filament Change Function  ##############################

#the speed to extrude filament(mm/min)
>cfg_filament_load_speed:1200
#the lenght to extrude filament (mm)
>cfg_filament_load_length:200

#the speed to retract filament(mm/min)
>cfg_filament_unload_speed:1200
#the lenght to retract filament(mm)
>cfg_filament_unload_length:200

#It is the minimum temperature for filament change.
It will auto heat up if the current temp doesn't reach the target.
>cfg_filament_load_limit_temperature:200


#---------------------------------------------------------------------------

############  Leveling Function  ########################################

#leveling mode(manual:0; auto:1; conceal leveling button:2)
>cfg_leveling_mode:0

#the command of auto leveling (G29 is available for Marlin.While G32 is for  Repetier and Smoothieware)
>cfg_auto_leveling_cmd:G28;G29;

#the point number of manual leveling:(3,4,5 point available)
>cfg_point_number:3

#the coordinates of 5 point on manual leveling
>cfg_point1:50,50
>cfg_point2:180,50
>cfg_point3:180,180
>cfg_point4:50,180
>cfg_point5:150,150

#the travel speed of leveling(mm/min)
>cfg_leveling_z_speed:1500
>cfg_leveling_xy_speed:3000

#---------------------------------------------------------------------------
 
#############  WIFI Function  ##########################################

#wifi model(MKS WIFI TFT:0;  MKS HLK-WIFI:1)
>cfg_wifi_type:0

#wifi mode(AP:1; STA:2)
>cfg_wifi_mode:1

#wifi name and password
>cfg_wifi_ap_name:MKS_wifi
>cfg_wifi_key_code:makerbase

#0:disable cloud service 1:enable cloud service
>cfg_cloud_enable:1
#cloud service adress
>cfg_wifi_cloud_host:www.baizhongyun.cn
#cloud service port
>cfg_cloud_port:10086

#Dynamic access IP
>cfg_ip_dhcp_flag:1

#IP/mask/gateway
>cfg_ip_address:192.168.3.100
>cfg_ip_mask:255.255.255.0
>cfg_ip_gate:192.168.3.1

#--------------------------------------------------------------------------------

############## Function Customization #######################################

#user-defined function1 and 2.(display this button .  disable: 0; enable: 1)
>cfg_function_btn1_display:1
>cfg_function_btn2_display:0

#command of user-defined function
>function_btn1_cmd:M84;
>function_btn2_cmd:M81;

#set number of  "More" button 
>moreitem_pic_cnt:0

#edit command for 1~7 "More" button,each command must be separated by semicolon ";"
>moreitem_button1_cmd:G28 X0;

>moreitem_button2_cmd:G28 X0;

>moreitem_button3_cmd:G28 Y0;

>moreitem_button4_cmd:G28 Y0;

>moreitem_button5_cmd:G28 Z0;

>moreitem_button6_cmd:G28 Z0;

>moreitem_button7_cmd:G28;

#how many "More" button display on screen interface
>morefunc_cnt:0

#command setting on button1~6
>morefunc1_cmd:G28;
>morefunc2_cmd:G28;
>morefunc3_cmd:G28;
>morefunc4_cmd:G28;
>morefunc5_cmd:G28;
>morefunc6_cmd:G28;

#---------------------------------------------------------------------------------
##### Display Customization(button and logo customized see User's Manual) #######

#the color of screen background
>cfg_background_color:0x000000

#the color of title text
>cfg_title_color:0xFFFFFF

#the color of temperature,fan,(etc) background
>cfg_state_background_color:0x000000

#the color of temprature,fan,(etc) text
>cfg_state_text_color:0xFFFFFF

#the color of file button
>cfg_filename_background_color:0x000000

#the color of file text
>cfg_filename_color:0xFFFFFF

#the color of background in printing 
>cfg_printingstat_word_background_color:0x000000

#the color of text in printing status
>cfg_printingstat_word_color:0xFFFFFF

#3D effects setting (disable: 0; enable: 1)
>cfg_BUTTON_3D_effects:0

#????180°(0:???,1:??)
>cfg_OVERTURN_180:0


# Levelling strategy

# Example for the delta calibration strategy
leveling-strategy.delta-calibration.enable   false            
leveling-strategy.delta-calibration.radius   100             

# Example for the delta grid leveling strategy
leveling-strategy.delta-grid.enable          false            
#leveling-strategy.delta-grid.radius          50              
#leveling-strategy.delta-grid.size            7               
#leveling-strategy.delta-grid.do_home         true            
#leveling-strategy.delta-grid.save            true            
#leveling-strategy.delta-grid.initial_height  10              


## System configuration
# Serial communications configuration 
# For communication over the UART port, *not* the USB/Serial port
uart0.baud_rate                              115200           

second_usb_serial_enable                     false            
#leds_disable                                true             
#play_led_disable                            true             

# network settings
network.enable                               false          # enable the ethernet network services
network.webserver.enable                     true             # enable the webserver
network.telnet.enable                        true             # enable the telnet server
network.plan9.enable                         false             # enable the plan9 network filesystem
network.ip_address                           auto             # use dhcp to get ip address

# Kill button maybe assigned to a different pin, 
# See http://smoothieware.org/killbutton
kill_button_enable                           false            
kill_button_pin                              2.12             

#msd_disable                                 false            
#dfu_enable                                  false            

# Only needed on a smoothieboard
# See http://smoothieware.org/currentcontrol
currentcontrol_module_enable                 true

**Comment by undertowx** [comment]
I know there isnt a problem with the cartridge heater because I swapped out to the Fan wiring on the board and the heater warmed up when I enabled the fan pin.. I tested the P2.7 pin and no volts are going to it and led does not light?

**Comment by undertowx** [comment]
was the thermistor.
