### ISSUE TITLE
Problem with RepRap Discount smart lcd?

### ISSUE THREAD

**Issue by siblues** [makerbase-mks/MKS-SBASE#72]
I am using the 12864 smart lcd on a MKS v1.3.I am new to all of this and have never had to set up a printer controller.I am just trying to get the panel working before I start trying to set up the board for use.I am using a usb to power up the board and panel/lcd.I do not know if it needs to be powered by a psu in order for the panel/lcd to function properly.Here is my config setup so far I only changed the leveling and panel sections and added a custom menu.The  LCD powers on but does not display any text it is blank.The knob/encoder beeps when it is pressed bu the screen is blank.

My config

## Z-probe
# See http://smoothieware.org/zprobe
zprobe.enable                                false           # Set to true to enable a zprobe
zprobe.probe_pin                             1.28!^          # Pin probe is attached to, if NC remove the !
zprobe.slow_feedrate                         5               # Mm/sec probe feed rate
#zprobe.debounce_count                       100             # Set if noisy
zprobe.fast_feedrate                         100             # Move feedrate mm/sec
zprobe.probe_height                          5               # How much above bed to start probe
#gamma_min_endstop                           nc              # Normally 1.28. Change to nc to prevent conflict,

# Levelling strategy
# Example for rectangular grid levelling strategy, see wiki documentation for other strategies
leveling-strategy.rectangular-grid.enable               true     # The strategy must be enabled in the config, as well as the zprobe module.
leveling-strategy.rectangular-grid.x_size               75       # size of bed in the X axis
leveling-strategy.rectangular-grid.y_size               50       # size of bed in the Y axis
leveling-strategy.rectangular-grid.size                 7 	 # The size of the grid, for example, 7 causes a 7x7 grid with 49 points. 
                                                                 # Must be an odd number.
leveling-strategy.rectangular-grid.do_home              true              
leveling-strategy.rectangular-grid.probe_offsets        0,0,0    # Optional probe offsets from the nozzle or tool head
leveling-strategy.rectangular-grid.save                 false    # If the saved grid is to be loaded on boot then this must be set to true
leveling-strategy.rectangular-grid.initial_height       10       # will move to Z10 before the first probe
leveling-strategy.rectangular-grid.dampening_start      0.5      # compansation decrease point (optional)
leveling-strategy.rectangular-grid.height_limit         1        # no compensation to apply after this point (optional)
mm_per_line_segment                                     1        # necessary for cartesians using rectangular-grid

## Panel
# See http://smoothieware.org/panel
# Please find your panel on the wiki and copy/paste the right configuration here
panel.enable                                 true              # Set to true to enable the panel code
# Example for reprap discount GLCD
# on glcd EXP1 is to left and EXP2 is to right, pin 1 is bottom left, pin 2 is top left etc.
# +5v is EXP1 pin 10, Gnd is EXP1 pin 9
# Panel settings
panel.enable                          true              # set to true to enable the panel code
panel.lcd                             reprap_discount_glcd     # set type of panel
panel.spi_channel                     0                 # spi channel to use  ; GLCD EXP1 Pins 3,5 (MOSI, SCLK)
panel.spi_cs_pin                      0.16              # spi chip select     ; GLCD EXP1 Pin 4
panel.encoder_a_pin                   3.26!^            # encoder pin         ; GLCD EXP2 Pin 3
panel.encoder_b_pin                   3.25!^            # encoder pin         ; GLCD EXP2 Pin 5
panel.click_button_pin                1.30!^            # click button        ; GLCD EXP1 Pin 2
panel.buzz_pin                        1.31              # pin for buzzer      ; GLCD EXP1 Pin 1
panel.back_button_pin                 2.11!^            # 2.11 menu back      ; GLCD EXP2 Pin 8
# setup for external sd card on the GLCD which uses the onboard sdcard SPI port
panel.external_sd                     true              # set to true if there is an extrernal sdcard on the panel
panel.external_sd.spi_channel         1                 # set spi channel the sdcard is on
panel.external_sd.spi_cs_pin          0.28              # set spi chip select for the sdcard (or any spare pin)
panel.external_sd.sdcd_pin            0.27!^            # sd detect signal (set to nc if no sdcard detect) (or any spare pin)

panel.menu_offset                            0                 # Some panels will need 1 here

panel.alpha_jog_feedrate                     6000              # X jogging feedrate in mm/min
panel.beta_jog_feedrate                      6000              # Y jogging feedrate in mm/min
panel.gamma_jog_feedrate                     200               # Z jogging feedrate in mm/min

panel.hotend_temperature                     185               # Temp to set hotend when preheat is selected
panel.bed_temperature                        60                # Temp to set bed when preheat is selected

## Custom menus : Example of a custom menu entry, which will show up in the Custom entry.
# NOTE _ gets converted to space in the menu and commands, | is used to separate multiple commands
custom_menu.power_on.enable                true              #
custom_menu.power_on.name                  Power_on          #
custom_menu.power_on.command               M80               #

custom_menu.power_off.enable               true              #
custom_menu.power_off.name                 Power_off         #
custom_menu.power_off.command              M81               #

custom_menu.filament_change_c.enable               true                                                   #
custom_menu.filament_change_c.name                 Change Filament                                        #
custom_menu.filament_change_c.command              G91|G1_Z0.6_F12000|G90|G1_X0_Y0|G91|G1_Z-0.6|G90|M25   #

custom_menu.filament_change_r.enable               true              #
custom_menu.filament_change_r.name                 Resume            #
custom_menu.filament_change_r.command              M24               #``

**Comment by pixel3design-hub** [comment]
don't know if it's your case, but AFAIK the two EXP1 & EXP2 have been placed turned 180°CW on MKS boards.
[EXP Connectors](https://drive.google.com/file/d/1LlnB5Pf5-WGBj6iMN_FiHVgEVf0d4sQG/view?usp=sharing
https://drive.google.com/file/d/1tbIESfJm76sxT8cShJpTWiNxdo9ATae4/view?usp=sharing)

As you can see the arrow pointing down on the left side, indicates the pin 1 of the connector.
In the other photo you see clearly the square pad that's indicating the pin 1.
The connector is turned by 180°. Your cables are marked on one side with a (normally) red line, which indicates the pin 1 of the ribbon cable.

The easiest approach for noobies is to grind the tab on the cable connectors to be able to put them in without recrimp everything.

Hope this would help.

Cheers

**Comment by siblues** [comment]
``Thanks but mine are already flipped.I figured out the problem anyway the contrast on the LCD was really bad and the potentiometer wasn't enough to fix it.The pot on the bottom of the actual LCD that is sandwiched between the pcb and LCD needs to be adjusted but I can't get to it.You can also pry the plastic housings off the pins and flip them around then press them back onto the pins.

**Comment by makerbase-mks** [comment]
@siblues  EXP1 should connect to EXP1,   EXP2 should be connect to EXP2.

**Comment by makerbase-mks** [comment]
@siblues EXP1 should be connect to EXP1, EXP2 should be connect to EXP2.

**Comment by waran14** [comment]
@siblues did you have to still flip the EXP 1, 2 connectors on the MKS SBASE board ? Also, did you make any other change to the config file ?

**Comment by siblues** [comment]
I just flipped them on the back of the lcd and selected the glcd in the config. I gave up on that lcd and am currently using the 3.2 TFT

**Comment by waran14** [comment]
EDIT: ISSUE RESOLVED
followed @pixel3design-hub instructions. used a dremel to sand down the tab and invert the ribbon cables such that the red wire is facing the motor pins ( or aligned to the square pin that is found on the bottom side)

Now the LCD is powering up correctly. thanks everyone.

added panel.encoder_resolution to help with encoder steps

SD card still not being detected

-----

alright. I tried swapping the cables and connector. The LCD is not even powering on. but the encoder wheel seems to do something. I am not sure at this point if this is related to pins on the LCD itself. But you mentioned something about the contrast not set correctly. how were you able to pry open the LCD without bending or breaking the pins soldered to the pcb ?

**Comment by siblues** [comment]
I broke one lcd and decided to just go with the TFT.

**Comment by waran14** [comment]
@pixel3design-hub do you have the Full Graphics (12864) or the standard graphics controller ? I am unable to find options to invert the encoder direction and the steps per rotation. 

Per rotation it is going 2 lines. Not sure what options to change. Here is my panel section


panel.enable                                 true             # Set to true to enable the panel code

# Example for reprap discount GLCD
# on glcd EXP1 is to left and EXP2 is to right, pin 1 is bottom left, pin 2 is top left etc.
# +5v is EXP1 pin 10, Gnd is EXP1 pin 9
panel.lcd                                   reprap_discount_glcd     #
panel.spi_channel                           0                 # SPI channel to use  ; GLCD EXP1 Pins 3,5 (MOSI, SCLK)
panel.spi_cs_pin                            0.16              # SPI chip select     ; GLCD EXP1 Pin 4
panel.encoder_a_pin                         3.25!^            # Encoder pin         ; GLCD EXP2 Pin 3
panel.encoder_b_pin                         3.26!^            # Encoder pin         ; GLCD EXP2 Pin 5
panel.click_button_pin                      1.30!^            # Click button        ; GLCD EXP1 Pin 2
panel.buzz_pin                              1.31              # Pin for buzzer      ; GLCD EXP1 Pin 1
panel.back_button_pin                       2.11!^            # Back button         ; GLCD EXP2 Pin 8

panel.menu_offset                            0                 # Some panels will need 1 here

panel.alpha_jog_feedrate                     6000              # X jogging feedrate in mm/min
panel.beta_jog_feedrate                      6000              # Y jogging feedrate in mm/min
panel.gamma_jog_feedrate                     200               # Z jogging feedrate in mm/min

panel.hotend_temperature                     185               # Temp to set hotend when preheat is selected
panel.bed_temperature                        60                # Temp to set bed when preheat is selected

**Comment by pixel3design-hub** [comment]
OMG... Not not not.
Is swapped pinwise, not connector wise... JC...

**Comment by waran14** [comment]
@pixel3design-hub Is your SD card slot being read correctly ? I am having issues with my SD card being read. I tried 2 different cards. On the LCD menu, I have 2 options
1. EXT and 2. SD. So, am guessing firmware is doing okay

**Comment by Filcanna** [comment]
THIS WORKED FOR ME TO MAKE LCD RECOGNIZED BY THE BOARD :D :D 
# Example for reprap discount GLCD
# on glcd EXP1 is to left and EXP2 is to right, pin 1 is bottom left, pin 2 is top left etc.
# +5v is EXP1 pin 10, Gnd is EXP1 pin 9
panel.spi_frequency        400000	
panel.lcd                                   reprap_discount_glcd  #st7565_glcd     #
panel.spi_channel                           0                 # SPI channel to use  ; GLCD EXP1 Pins 3,5 (MOSI, SCLK)
panel.spi_cs_pin                            0.16              # SPI chip select     ; GLCD EXP1 Pin 4
panel.encoder_a_pin                         3.25!            # Encoder pin         ; GLCD EXP2 Pin 3
panel.encoder_b_pin                         3.26!            # Encoder pin         ; GLCD EXP2 Pin 5
panel.click_button_pin                      1.30!^            # Click button        ; GLCD EXP1 Pin 2
panel.buzz_pin                              1.31              # Pin for buzzer      ; GLCD EXP1 Pin 1
panel.back_button_pin                       2.11!^            # Back button         ; GLCD EXP2 Pin 8
panel.encoder_resolution                    4
panel.menu_offset                            0                 # Some panels will need 1 here

#panel.external_sd.spi_channel 		0 
#panel.external_sd.spi_cs_pin 		2.8
#panel.external_sd.sdcd_pin 		2.13!^

Note: spi clock frequency explicitly declared (on LPC1768 system clock is 96 MHz, in Smoothieboard LPC1769 is 120 MHz so I proportionally adapted SPI clock); ^ character removed from encoder pins setting (CW rotation moves menu down); resolution of encoder set to 4; my try to have an external SD card was aborted :(
