### ISSUE TITLE
PT100 NOT WORKING 

### ISSUE THREAD

**Issue by anrual** [makerbase-mks/MKS-SBASE#78]
Hello 

I use de Firmware of MKS Sbase, with PT100. 

But  Is not Working 

The last firmware of smoothiware add E3D amplifier, firmware of MKS Sbase is compatible with that

Somebody have de Config.txt and Firmware for this configuration 

Thaks

**Comment by pixel3design-hub** [comment]
You will find it on smoothieware site. But beware that they modified the firmware to not work reliably on MKS boards. I found skipping a Lot of steps with latest firmwares... The latest working build is from agoust 2017

**Comment by anrual** [comment]
MKS BASE, it possible update firmware, for PT100 E3D work properly, with MKS SBASE?

it's possible change the last firmware smoothieware for work on MKS SBASE?
