### ISSUE TITLE
MKS SBASE 1.3v Skewed Prints and poor quality 

### ISSUE THREAD

**Issue by phylyprobert** [makerbase-mks/MKS-SBASE#85]
Hi, I’m building a large Cartesian using Tb6600 external drivers with Nema 23 motors... I print very slowly and still getting skewed prints on YX axis. Let’s say I print a tower, it will be leaning -X -Y. I tried to reflash the firmware and config file in a new SD card and it worked fine for a hour, In the first reset, it went to leaning prints. The problem is not mechanical because I get PERFECT prints with Marlin. Please help. Thank you very much

**Comment by FCam1** [comment]
It seems to be a problem of missing steps. Are you sure about your max values in the config.txt. Are you sure your last config.txt is taking in account by the board ? 
Personally I found differences in the max acc,speed passing from marlin to smoothieware. Moreover after some writes/resets my modifications were no longer taken in account so I had to format the SD card (data corrupted ).
