### ISSUE TITLE
Endstop keeps triggered after homing

### ISSUE THREAD

**Issue by KuroiSabato** [makerbase-mks/MKS-SBASE#87]
Have a new issue that just can't fix.
my endstops (x,y,z) does not untrigger after homing the first time.

better explained: after turning the machine on; can check using M119:

SENT: M119
READ: X_min:0 Y_min:0 Z_min:0 pins- (X)P1.24:1 (Y)P1.26:1 (Z)P1.28:1 (Z)P1.29:1  Probe: 0

after HOMING the carriage:
SENT: M119
READ: X_min:1 Y_min:1 Z_min:1 pins- (X)P1.24:1 (Y)P1.26:1 (Z)P1.28:1 (Z)P1.29:1  Probe: 0

later, after homing and MOVING the carriage to any other place on the bed:
SENT: M119
READ: X_min:1 Y_min:1 Z_min:1 pins- (X)P1.24:1 (Y)P1.26:1 (Z)P1.28:1 (Z)P1.29:1  Probe: 0

it minds: the endstops does not change back to untrigger (pos.0)

can you give me a light on this issue?

my endstop conf.

######################################################## Endstops

# See http://smoothieware.org/endstops
endstops_enable                              true             # The endstop module is enabled by default and can be disabled here
corexy_homing                                true             # Set to true if homing on a hbot or corexy
alpha_min_endstop                            1.24^            # Pin to read min endstop, add a ! to invert if endstop is NO connected to ground
#alpha_max_endstop                           1.25^            # Pin to read max endstop, uncomment this and comment the above if using max endstops
alpha_homing_direction                       home_to_min      # Or set to home_to_max and set alpha_max and uncomment the alpha_max_endstop
alpha_min                                    0                # This gets loaded as the current position after homing when home_to_min is set
alpha_max                                    300              # This gets loaded as the current position after homing when home_to_max is set
beta_min_endstop                             1.26^            # Pin to read min endstop, add a ! to invert if endstop is NO connected to ground
#beta_max_endstop                            1.27^            # Pin to read max endstop, uncomment this and comment the above if using max endstops
beta_homing_direction                        home_to_min      # Or set to home_to_max and set alpha_max and uncomment the alpha_max_endstop
beta_min                                     0                # This gets loaded as the current position after homing when home_to_min is set
beta_max                                     300              # This gets loaded as the current position after homing when home_to_max is set
gamma_min_endstop                            1.28!^           # Pin to read min endstop, add a ! to invert if endstop is NO connected to ground
gamma_max_endstop                            1.29^            # Pin to read max endstop, uncomment this and comment the above if using max endstops
gamma_homing_direction                       home_to_min      # Or set to home_to_max and set alpha_max and uncomment the alpha_max_endstop
gamma_min                                    0                # This gets loaded as the current position after homing when home_to_min is set
gamma_max                                    500              # This gets loaded as the current position after homing when home_to_max is set

alpha_max_travel                             300              # Max travel in mm for alpha/X axis when homing
beta_max_travel                              300              # Max travel in mm for beta/Y axis when homing
gamma_max_travel                             500              # Max travel in mm for gamma/Z axis when homing

# Optional enable limit switches, actions will stop if any enabled limit switch is triggered
#alpha_limit_enable                          false            # Set to true to enable X min and max limit switches
#beta_limit_enable                           false            # Set to true to enable Y min and max limit switches
#gamma_limit_enable                          false            # Set to true to enable Z min and max limit switches

# Endstops home at their fast feedrate first, then once the endstop is found they home again at their slow feedrate for accuracy
alpha_fast_homing_rate_mm_s                  100              # Alpha/X fast homing feedrate in mm/second
alpha_slow_homing_rate_mm_s                  20               # Alpha/X slow homing feedrate in mm/second
beta_fast_homing_rate_mm_s                   100              # Beta/Y  fast homing feedrate in mm/second
beta_slow_homing_rate_mm_s                   20               # Beta/Y  slow homing feedrate in mm/second
gamma_fast_homing_rate_mm_s                  50               # Gamma/Z fast homing feedrate in mm/second
gamma_slow_homing_rate_mm_s                  8                # Gamma/Z slow homing feedrate in mm/second

alpha_homing_retract_mm                      5                # Distance to retract from the endstop after it is hit for alpha/X
beta_homing_retract_mm                       5                # Distance to retract from the endstop after it is hit for beta/Y
gamma_homing_retract_mm                      5                # Distance to retract from the endstop after it is hit for gamma/Z

**Comment by KuroiSabato** [comment]
ok... I guess it's enough. Last MKS product ever.

**Comment by Pixel3DesignITA** [comment]
are your endstops conneted to gnd?
are they simple pulse switches or the ones with 3 wires and monted on a pcb?

Try to remove the pullup ^ from the config of ONE switch and check again.
If the second option (switch over pcb) is true, then absolutely remove the pullup ^ frome config, because the red wire is connected to +5v (or 3.3v if selected on the board) and 2 pullups are not good anyway and can cause problems.
Switches MUST be connected:
ALPHA & BETA & GAMMA -> Normally Opened and pulled Up and connected between GND and SIG
alpha_min_endstop 1.24!^
beta_min_endstop 1.26!^
gamma_min_endstop 1.28!^

Check and write back.

Disclaimer:
I'm NOT an MKS people. I justa have various MKS boards for my printers. Just here to help.
Cheers!

**Comment by KuroiSabato** [comment]
Ciao. Thanks for the response.
Yeh, everything is configured as it should.  It was working and somehow,  for an unknown reason, not anymore.
Had changed the board, (as am building many machines and luckily have 3 more boards to spare) an all is fixed. <- just to let mks guys to know, what kind if client they are loosing.

So, like I said... moving to another brand, maybe to the original smoothboard. Just giving up of this TERRIBLE CUSTOMER SERVICE. Shame!!!

Grazie mille, caro.

**Comment by Pixel3DesignITA** [comment]
Di nulla...

**Comment by loefstrand** [comment]
Hi!
I found that R33, R34, R35, R39, R40 & R41 has a incorrect value (1K instead of 10K) on my MKS SBASE V1.3. This makes my optocoupler end stops fail. The optocouplers can't pull a correct 0V, instead I get ~1.1V due to the "strong" pullup resistors.

I have changed the resistors on my board with the correct value (10K) and now the end stops works :)

I saw that even early BOM:s from the source has the same incorrect value on the resistors. So please update your BOM with the correct values.

/// Marcus
