### ISSUE TITLE
Firmware version

### ISSUE THREAD

**Issue by Operrr** [makerbase-mks/MKS-SBASE#92]
Greetings to all!

Dear developers, I purchased your product and I want to be sure that I have the newest firmware. Available for download version released 2 years ago. Is the project no longer supported? Or do you update this file? Where and how can I view the firmware version?

**Comment by pixel3design-hub** [comment]
Oh dear... I'm so sorry dude, but the firmware is developed by Smoothieware. Maker Base does not support their  customers, nor Smoothieware. They never had. And because of that, smoothieware project does not support us... Fun uh?

**Comment by ingfdoaguirre** [comment]
Use marlin 2

**Comment by bilou24an199** [comment]
Hello Everybody ans happy New year
Concernant the firmware from mks which is dedicate to sbase some gcode fonction are missing like doing a pause during printing i only make a timer but not a Real pause. My question is : is it possible to install std smoothieware firmware instead or mks once. Is it risky for the sbase or not

**Comment by Operrr** [comment]
I always install the latest firmware, there are no problems, it works fine

**Comment by bilou24an199** [comment]
Thanks Operrr for your answer. I have installed the firmware from smoothie original, it works normally but when I ask the version I have a warning concerning the MLS board which is not a good one. But it works

**Comment by 3Dangel** [comment]
I have my Sbase using the Marlin 2
Cheers

**Comment by makerbase-mks** [comment]
Sbase motherboards are supported for Smoothieware firmware, and Marlin2 also supports SBASE and continues to improve.
