### ISSUE TITLE
Sudden stoppage of the board (MKS Sbase 1.3)

### ISSUE THREAD

**Issue by nico757** [makerbase-mks/MKS-SBASE#93]
Hello,

During a print, my printer has suddenly turned off. It never turned on again, by usb and by 12V DC in. I've tested the fuse F1, F2 and F3 and didn't find any problem.

Have you ever had this problem ? My card is died ?

Thanks You :)

**Comment by jovo0911** [comment]
Same here - prints for any day's without problems - and then it stop's without any log entry's

Bullshit didn't work with smoothieware  - I'll put in trash it waste my time .......

**Comment by nico757** [comment]
what did you buy instead?

**Comment by jovo0911** [comment]
Duet Meastro !!

You can try the RepRap Firmware for "MKS SBASE" to see what this software can do - absolute great.
    https://reprap.org/forum/read.php?147,810214,810214
this show me that y temperature goes up and down(you can say - spikes - between 5 to 10°C. The developer said smoothie ask not so often and fllter that.

**Comment by nico757** [comment]
Nobody else ? :(

**Comment by makerbase-mks** [comment]
You can measure whether the rectifier diode next to or in front of the power supply terminal is broken down (S1A, S1G). Generally, it is a one-way conduction.

**Comment by nico757** [comment]
Thank you, I will check the diode. :)

**Comment by ChrisWeiss** [comment]
In case someone finds this by googling - S1A is most likely to burn out if you wire the power incorrectly.
