### ISSUE TITLE
Manual control is not working

### ISSUE THREAD

**Issue by Nhanzz** [makerbase-mks/MKS-SBASE#97]
Hi,
I don't know is the right place to ask, We have been developing a Hbot Cartesian 3d printer. The project is in the testing stage
the following are the specifications
- Bed size: 750x750x750
- Control board: MKS S bord 
- Firmware used: Smoothieware
- Leveling sensor: Geeetech auto leveling sensor
- Software used: Repetier Host

There are some issues regarding our development.
In our case, the Z+ port is connected to the bed leveling sensor. In the configuration file, the direction of limiting switch is from "home to min". The homing is ok but while using manual control mode in repetier software, the warning message is coming "one fatal error" when Z+ is hit.
Thanks

![whatsapp image 2019-02-05 at 7 39 15 pm 1](https://user-images.githubusercontent.com/47390935/52349651-04a0b480-2a4d-11e9-85c8-667c4964a382.jpeg)
![whatsapp image 2019-02-05 at 8 02 03 pm](https://user-images.githubusercontent.com/47390935/52349774-40d41500-2a4d-11e9-8e94-fe2c41e1da4d.jpeg)

**Comment by makerbase-mks** [comment]
Hi! Can the problem be solved by switching the upper computer? Example: pronterface.
