### ISSUE TITLE
Hardware schematic please see the 'Hardware' folder

### ISSUE THREAD

**Issue by DivingDuck** [makerbase-mks/MKS-SBASE#99]
I can't believe what I see - a miracle...
After looking to the schematics pdf file I believe the file readme is wrong: MKS SGEN hardware schematic:MKS SGEN V1.0_001 SCH.pdf
Best regards, DD

PS: It would be very nice to provide also something like Eagle or KiCAD files :)

**Comment by makerbase-mks** [comment]
Yes, we have now developed a schematic of sbase and sgen
